/** Centre de suivi PFMP — dev.22, vue historique de recette strictement en lecture seule. */
var EUC_SUIVI_VERSION_='Eucalyptus PFMP — v1.0.0-dev.22';
var EUC_SUIVI_COHORTE_HISTORIQUE_='PRONOTE_2025_2026_TEST';
var EUC_SUIVI_ANNEE_HISTORIQUE_='2025-2026';
var EUC_SUIVI_ROLES_ = ['ADMIN_PFMP','DDFPT','BUREAU_ENTREPRISES','ENSEIGNANT','LECTURE_SEULE'];
var EUC_SUIVI_PERMISSIONS_ = {
  ADMIN_PFMP:{tout:true,modifier:true,saisir:true,annuler:true,purgerTests:true},
  DDFPT:{tout:true,modifier:true,saisir:true,annuler:true,purgerTests:false},
  BUREAU_ENTREPRISES:{tout:true,modifier:true,saisir:true,annuler:true,purgerTests:false},
  ENSEIGNANT:{tout:false,modifier:false,saisir:false,annuler:false,purgerTests:false},
  LECTURE_SEULE:{tout:false,modifier:false,saisir:false,annuler:false,purgerTests:false}
};
function EUC_SUIVI_nettoyer_(v,max){return String(v==null?'':v).trim().slice(0,max||5000);}
function EUC_SUIVI_construireContexteUtilisateur_(email,lignes){
  email=EUC_SUIVI_nettoyer_(email,250).toLowerCase();
  var ligne=(lignes||[]).filter(function(r){var f=r.fields||r;return f.Actif!==false&&EUC_SUIVI_nettoyer_(f.Email,250).toLowerCase()===email;})[0];
  if(!email||!ligne) return {autorise:false,message:'Accès non autorisé.'};
  var f=ligne.fields||ligne,role=EUC_SUIVI_nettoyer_(f.Role,50).toUpperCase();
  if(EUC_SUIVI_ROLES_.indexOf(role)<0)return {autorise:false,message:'Accès non autorisé.'};
  var base=EUC_SUIVI_PERMISSIONS_[role],classes=Array.isArray(f.Classes_autorisees)?f.Classes_autorisees:String(f.Classes_autorisees||'').split(',').map(function(x){return EUC_SUIVI_nettoyer_(x,100);}).filter(Boolean),lectureSeule=String(f.Mode_acces||'').toUpperCase()==='LECTURE_SEULE';
  return {autorise:true,email:email,nom:EUC_SUIVI_nettoyer_(f.Nom_affichage,150),role:role,classes:classes,peutVoirToutesClasses:f.Peut_voir_toutes_classes===true||base.tout,peutModifier:!lectureSeule&&(f.Peut_modifier===true||base.modifier),peutSaisir:!lectureSeule&&(f.Peut_saisir===true||base.saisir),peutAnnuler:!lectureSeule&&(f.Peut_annuler===true||base.annuler),peutPurgerTests:!lectureSeule&&(f.Peut_purger_tests===true||base.purgerTests),lectureSeule:lectureSeule};
}
function EUC_SUIVI_exiger_(ctx,droit){if(!ctx||!ctx.autorise||(droit&&!ctx[droit]))throw new Error('Accès non autorisé.');return true;}
function EUC_SUIVI_classeAutorisee_(ctx,f){if(ctx.peutVoirToutesClasses)return true;var valeurs=[f.Classe,f.Classe_snapshot].map(String);return ctx.classes.some(function(x){return valeurs.indexOf(String(x))>=0;});}
function EUC_SUIVI_vueListe_(r){var f=r.fields||r;return {id:r.id||f.id,reference:f.Reference||'',classe:f.Classe_snapshot||'',nom:f.Jeune_nom||'',prenom:f.Jeune_prenom||'',statut:f.Statut_jeune||'',periode:f.Periode_snapshot||'',dateDebut:f.Date_declaree_debut||'',dateFin:f.Date_declaree_fin||'',entreprise:f.Entreprise_raison_sociale_snapshot||'',ville:f.Entreprise_commune_snapshot||'',pays:f.Entreprise_pays_snapshot||'',responsable:f.Responsable_nom||'',tuteur:f.Tuteur_nom||'',telephone:f.Jeune_telephone||'',courriel:f.Jeune_courriel||'',etat:f.Statut_administratif||'',pronote:f.Traite_dans_Pronote===true?'TRAITE':(f.A_traiter_dans_Pronote===false?'NON_REQUIS':'A_TRAITER'),modifieLe:f.Date_modification||'',version:f.Version_suivi||f.Date_modification||''};}
function EUC_SUIVI_filtrerEtPaginer_(lignes,ctx,filtres){
  EUC_SUIVI_exiger_(ctx);filtres=filtres||{};var q=EUC_SUIVI_nettoyer_(filtres.recherche,200).toLowerCase(),page=Math.max(1,Number(filtres.page)||1),taille=Math.min(100,Math.max(1,Number(filtres.taille)||25));
  var rows=(lignes||[]).filter(function(r){var f=r.fields||r;if(!EUC_SUIVI_classeAutorisee_(ctx,f))return false;if(filtres.classe&&String(f.Classe_snapshot)!==String(filtres.classe))return false;if(filtres.periode&&String(f.Periode_officielle)!==String(filtres.periode)&&String(f.Periode_snapshot)!==String(filtres.periode))return false;if(filtres.etat&&String(f.Statut_administratif)!==String(filtres.etat))return false;if(filtres.annee&&String(f.Annee_scolaire)!==String(filtres.annee)&&String(f.Annee_libelle_snapshot)!==String(filtres.annee))return false;if(!q)return true;return [f.Reference,f.Classe_snapshot,f.Jeune_nom,f.Jeune_prenom,f.Entreprise_raison_sociale_snapshot,f.Entreprise_commune_snapshot,f.Responsable_nom,f.Tuteur_nom].join(' ').toLowerCase().indexOf(q)>=0;}).map(EUC_SUIVI_vueListe_);
  var tri=['classe','nom','prenom','entreprise','etat','modifieLe'].indexOf(filtres.tri)>=0?filtres.tri:'modifieLe',sens=filtres.sens==='asc'?1:-1;rows.sort(function(a,b){return String(a[tri]||'').localeCompare(String(b[tri]||''),'fr')*sens;});var debut=(page-1)*taille;
  return {total:rows.length,page:page,taille:taille,lignes:rows.slice(debut,debut+taille)};
}
function EUC_SUIVI_detail_(ligne,ctx){EUC_SUIVI_exiger_(ctx);var f=ligne&&ligne.fields||ligne||{};if(!EUC_SUIVI_classeAutorisee_(ctx,f))throw new Error('Accès non autorisé.');return Object.assign({id:ligne.id||f.id},f);}
function EUC_SUIVI_diff_(avant,apres){var out=[];Object.keys(apres||{}).forEach(function(k){if(JSON.stringify((avant||{})[k])!==JSON.stringify(apres[k]))out.push(k);});return out;}
function EUC_SUIVI_simulerModification_(ligne,changements,ctx,options){
  EUC_SUIVI_exiger_(ctx,'peutModifier');options=options||{};var avant=Object.assign({},ligne.fields||ligne),version=String(avant.Version_suivi||avant.Date_modification||'');if(String(options.versionAttendue||'')!==version)throw new Error('La fiche a changé. Rechargez les données.');var motif=EUC_SUIVI_nettoyer_(options.motif,1000);if(!motif)throw new Error('Motif de la modification obligatoire.');var apres=Object.assign({},avant,changements||{}),champs=EUC_SUIVI_diff_(avant,apres);apres.Version_suivi=String((Number(avant.Version_suivi)||0)+1);apres.Date_modification=options.maintenant||new Date().toISOString();apres.Auteur_derniere_modification=ctx.email;if(avant.Traite_dans_Pronote===true&&champs.some(function(k){return ['Classe','Classe_snapshot','Periode_officielle','Date_declaree_debut','Date_declaree_fin','Entreprise','Entreprise_raison_sociale_snapshot'].indexOf(k)>=0;}))apres.Etat_traitement_Pronote='A_REVERIFIER_DANS_PRONOTE';return {dryRun:true,courant:apres,historique:{Soumission:ligne.id||avant.id,Version_avant:version,Version_apres:apres.Version_suivi,Type_action:options.typeAction||'CORRECTION',Champs_modifies:champs,Valeurs_avant_JSON:JSON.stringify(avant),Valeurs_apres_JSON:JSON.stringify(apres),Motif:motif,Auteur_email:ctx.email,Date_action:apres.Date_modification,Origine_action:'CENTRE_SUIVI'}};
}
function EUC_SUIVI_simulerAnnulation_(ligne,ctx,options){options=options||{};return EUC_SUIVI_simulerModification_(ligne,{Statut_administratif:'ANNULEE',Date_annulation:options.maintenant||new Date().toISOString(),Annule_par:ctx.email},ctx,{versionAttendue:options.versionAttendue,motif:options.motif,typeAction:'ANNULATION',maintenant:options.maintenant});}
function EUC_SUIVI_simulerPurge_(){throw new Error('Purge réelle interdite dans ce lot.');}
function EUC_SUIVI_simulerAffectation_(existantes,nouvelle,ctx){EUC_SUIVI_exiger_(ctx,'peutModifier');var maintenant=nouvelle.maintenant||new Date().toISOString(),sortie=(existantes||[]).map(function(x){var y=Object.assign({},x);if(y.Actif!==false&&String(y.Type_suivi)===String(nouvelle.Type_suivi)){y.Actif=false;y.Statut_affectation='REMPLACE';y.Date_fin=maintenant;}return y;});sortie.push({Soumission_PFMP:nouvelle.Soumission_PFMP,Professeur:nouvelle.Professeur,Email_professeur_snapshot:nouvelle.Email_professeur_snapshot||'',Nom_professeur_snapshot:nouvelle.Nom_professeur_snapshot||'',Type_suivi:nouvelle.Type_suivi,Date_affectation:maintenant,Date_debut:nouvelle.Date_debut||maintenant,Date_fin:null,Statut_affectation:nouvelle.Statut_affectation||'A_PLANIFIER',Affecte_par:ctx.email,Date_modification:maintenant,Commentaire:nouvelle.Commentaire||'',Actif:true});return {dryRun:true,affectations:sortie};}
function EUC_SUIVI_simulerVisite_(detail,affectation,ctx){EUC_SUIVI_exiger_(ctx);if(!ctx.peutVoirToutesClasses&&String(affectation.Email_professeur_snapshot||'').toLowerCase()!==ctx.email)throw new Error('Accès non autorisé.');return {dryRun:true,Soumission_PFMP:detail.id,Professeur:affectation.Professeur,Date_prevue:affectation.Date_prevue||'',Destination_snapshot:{raisonSociale:detail.Entreprise_raison_sociale_snapshot||'',nomCommercial:detail.Entreprise_enseigne_snapshot||'',adresse:detail.Entreprise_adresse_snapshot||'',complement:detail.Entreprise_complement_adresse_snapshot||'',codePostal:detail.Entreprise_code_postal_snapshot||'',ville:detail.Entreprise_commune_snapshot||'',pays:detail.Entreprise_pays_snapshot||'',responsable:detail.Responsable_nom||'',tuteur:detail.Tuteur_nom||'',telephone:detail.Tuteur_telephone||detail.Responsable_telephone||'',courriel:detail.Tuteur_courriel||detail.Responsable_courriel||''}};}
function EUC_SUIVI_simulerOrdreMission_(visite,precedent,ctx){EUC_SUIVI_exiger_(ctx,'peutModifier');return {dryRun:true,Visite:visite.id||'',Soumission_PFMP:visite.Soumission_PFMP,Professeur:visite.Professeur,Statut:'BROUILLON',Version_document:(Number(precedent&&precedent.Version_document)||0)+1,Adresse_destination_snapshot:JSON.stringify(visite.Destination_snapshot||{}),Identifiant_document:'',URL_document:'',Empreinte_document:''};}
function EUC_SUIVI_simulerFrais_(ordre,ctx){EUC_SUIVI_exiger_(ctx);if(!ctx.peutVoirToutesClasses&&String(ordre.Email_professeur_snapshot||'').toLowerCase()!==ctx.email)throw new Error('Accès non autorisé.');return {dryRun:true,Ordre_mission:ordre.id||'',Professeur:ordre.Professeur,Statut_dossier:'NON_OUVERT',Identifiant_document:'',URL_document:'',coordonneesBancaires:undefined};}
function EUC_SUIVI_exporterCSV_(lignes,ctx,filtres){var data=EUC_SUIVI_filtrerEtPaginer_(lignes,ctx,Object.assign({},filtres,{page:1,taille:100})).lignes,cols=['reference','classe','nom','prenom','statut','periode','dateDebut','dateFin','entreprise','ville','pays','etat','pronote'];return [cols.join(';')].concat(data.map(function(r){return cols.map(function(k){return '"'+String(r[k]||'').replace(/"/g,'""')+'"';}).join(';');})).join('\n');}

function EUC_SUIVI_dateGristISO_(v){if(typeof v==='number'&&isFinite(v))return new Date(v*1000).toISOString().slice(0,10);var s=String(v||'');return /^\d{4}-\d{2}-\d{2}$/.test(s)?s:'';}
function EUC_SUIVI_dateGristFR_(v){var s=EUC_SUIVI_dateGristISO_(v);return s?s.slice(8,10)+'/'+s.slice(5,7)+'/'+s.slice(0,4):'';}
function EUC_SUIVI_soumissionHistoriqueReelle_(r,annee){var f=r.fields||r,mode=String(f.Mode_soumission||f.Environnement||'').toUpperCase(),statut=String(f.Statut_administratif||'').toUpperCase(),a=String(f.Annee_libelle_snapshot||'');return mode!=='DRY_RUN'&&statut!=='SIMULATION'&&(!a||a===annee);}
function EUC_SUIVI_construireVueCohorteHistorique_(data,ctx,filtres){
  EUC_SUIVI_exiger_(ctx);data=data||{};filtres=filtres||{};var annee=String(filtres.annee||EUC_SUIVI_ANNEE_HISTORIQUE_),years=data.annees||[],year=years.filter(function(r){return String((r.fields||r).Code)===annee;})[0],yearId=year&&(year.id||(year.fields||year).id),q=EUC_SUIVI_normaliserRecherche_(filtres.recherche),page=Math.max(1,Number(filtres.page)||1),taille=Math.min(100,Math.max(1,Number(filtres.taille)||25));
  if(annee!==EUC_SUIVI_ANNEE_HISTORIQUE_||!yearId)return {version:EUC_SUIVI_VERSION_,annee:annee,total:0,page:page,taille:taille,lignes:[],compteurs:{libelle:'Effectif de recette '+annee,importes:0,presents:0,sortis:0,avecConvention:0,sansConvention:0,ambiguites:0,soumissionsHorsListe:0},filtres:{annees:years.map(function(r){return (r.fields||r).Code;}).filter(Boolean),classes:[],periodes:[],etats:['AVEC_CONVENTION','SANS_CONVENTION','AMBIGU']}};
  var planning=(data.periodes||[]).filter(function(r){return String((r.fields||r).Annee_scolaire)===annee;}),planningById={};planning.forEach(function(r){planningById[r.id||(r.fields||r).id]=r.fields||r;});var liens={};(data.liens||[]).forEach(function(r){var f=r.fields||r,p=planningById[f.Periode];if(f.Active!==false&&p){if(!liens[f.Offre_formation])liens[f.Offre_formation]=[];liens[f.Offre_formation].push(Object.assign({id:f.Periode},p));}});
  var submissions=(data.soumissions||[]).filter(function(r){return EUC_SUIVI_soumissionHistoriqueReelle_(r,annee);}),used={},allStudents=(data.eleves||[]).filter(function(r){var f=r.fields||r;return f.Annee_scolaire===yearId&&f.Donnee_test===true&&f.Mode_donnee==='RECETTE_HISTORIQUE'&&f.Cohorte_import===EUC_SUIVI_COHORTE_HISTORIQUE_&&f.Utilisable_production===false;}),rows=[];
  allStudents.forEach(function(r){var f=r.fields||r,classe=String(f.Code_classe_importe||''),nom=String(f.Nom||''),prenom=String(f.Prenom_usage||f.Prenom||''),periods=liens[f.Offre_formation]||[],match=submissions.filter(function(s){var sf=s.fields||s;return EUC_SUIVI_normaliserRecherche_(sf.Jeune_nom)===EUC_SUIVI_normaliserRecherche_(nom)&&EUC_SUIVI_normaliserRecherche_(sf.Jeune_prenom)===EUC_SUIVI_normaliserRecherche_(prenom)&&EUC_SUIVI_dateGristISO_(sf.Jeune_date_naissance)===EUC_SUIVI_dateGristISO_(f.Date_naissance);}),etat=match.length===1?'AVEC_CONVENTION':match.length>1?'AMBIGU':'SANS_CONVENTION';match.forEach(function(s){used[s.id||(s.fields||s).id]=true;});var sf=match.length===1?(match[0].fields||match[0]):{},sorti=f.Statut_scolarite==='SORTI'&&!!f.Date_sortie,periodLabels=periods.map(function(p){return p.Libelle_periode||p.Code_periode||p.Formation||'Période historique';}),dateLabels=periods.map(function(p){var d=EUC_SUIVI_dateGristFR_(p.Date_debut),fin=EUC_SUIVI_dateGristFR_(p.Date_fin);return d&&fin?d+' au '+fin:'';}).filter(Boolean);rows.push({id:r.id||f.id,nom:nom,prenom:prenom,classe:classe,periode:periodLabels.length?periodLabels.join(' · '):'Période historique non reliée',datesOfficielles:dateLabels.length?dateLabels.join(' · '):'',etatConvention:etat,entreprise:match.length===1?String(sf.Entreprise_raison_sociale_snapshot||''):'',statutScolarite:sorti?'SORTI':'PRESENT',badgeSortie:sorti?'Sorti le '+EUC_SUIVI_dateGristFR_(f.Date_sortie):'',periodeIds:periods.map(function(p){return String(p.id);})});
  });
  var soumissionsHorsListe=submissions.filter(function(s){return !used[s.id||(s.fields||s).id];}).length,base=rows.slice(),classes=Array.from(new Set(base.map(function(x){return x.classe;}).filter(Boolean))).sort(),periodeOptions=planning.map(function(p){var f=p.fields||p;return {id:String(p.id||f.id),label:f.Libelle_periode||f.Code_periode||f.Formation||'Période historique'};});
  rows=rows.filter(function(x){if(!EUC_SUIVI_classeAutorisee_(ctx,{Classe:x.classe,Classe_snapshot:x.classe}))return false;if(filtres.classe&&x.classe!==String(filtres.classe))return false;if(filtres.periode&&x.periodeIds.indexOf(String(filtres.periode))<0)return false;if(filtres.etat&&x.etatConvention!==String(filtres.etat))return false;if(filtres.scolarite&&x.statutScolarite!==String(filtres.scolarite))return false;if(q&&EUC_SUIVI_normaliserRecherche_(x.nom+' '+x.prenom).indexOf(q)<0)return false;return true;});
  var compteurs={libelle:'Effectif de recette '+annee,importes:rows.length,presents:rows.filter(function(x){return x.statutScolarite==='PRESENT';}).length,sortis:rows.filter(function(x){return x.statutScolarite==='SORTI';}).length,avecConvention:rows.filter(function(x){return x.etatConvention==='AVEC_CONVENTION';}).length,sansConvention:rows.filter(function(x){return x.statutScolarite==='PRESENT'&&x.etatConvention==='SANS_CONVENTION';}).length,ambiguites:rows.filter(function(x){return x.etatConvention==='AMBIGU';}).length,soumissionsHorsListe:soumissionsHorsListe};rows.sort(function(a,b){return (a.classe+'|'+a.nom+'|'+a.prenom).localeCompare(b.classe+'|'+b.nom+'|'+b.prenom,'fr');});var start=(page-1)*taille;
  return {version:EUC_SUIVI_VERSION_,annee:annee,total:rows.length,page:page,taille:taille,lignes:rows.slice(start,start+taille).map(function(x){var y=Object.assign({},x);delete y.periodeIds;return y;}),compteurs:compteurs,filtres:{annees:years.map(function(r){return String((r.fields||r).Code||'');}).filter(Boolean).sort(),classes:classes,periodes:periodeOptions,etats:['AVEC_CONVENTION','SANS_CONVENTION','AMBIGU']}};
}
function EUC_SUIVI_normaliserRecherche_(v){return String(v||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toUpperCase().replace(/[’'\-\s]+/g,' ').trim();}
