/** Eucalyptus PFMP — v1.0.0-dev.77 — prévisualisation et import réel enrichis. */
function EUC_IMPORT_chargerDonneesPreviewCompletV77_(annee,sourcePronote){
  var source=EUC_IMPORT_normaliserSourcePronote_(sourcePronote),existing=[],imports=[],responsables=[];
  try{existing=EUC_SUIVI_fields_(EUC_SUIVI_sqlLecture_("SELECT e.*,a.Code AS Annee_code FROM EUC_ELEVES_PFMP e JOIN Annees_Scolaires a ON a.id=e.Annee_scolaire WHERE a.Code=?",[annee]));existing=EUC_IMPORT_normaliserDatesExistantes_(existing);}catch(e){}
  if(source&&source!=='AUTO')existing=existing.filter(function(x){var s=EUC_IMPORT_normaliserSourcePronote_(x.Source_Pronote||x.Source_import||'');return !s||s===source;});
  try{imports=EUC_IMPORT_lireRecords_('EUC_IMPORTS_PRONOTE_PFMP').filter(function(i){var s=EUC_IMPORT_normaliserSourcePronote_(i.Source_Pronote||'');return !s||s===source;});}catch(e){}
  try{responsables=EUC_IMPORT_lireRecords_(EUC_IMPORT_RESP_TABLE_).filter(function(r){var s=EUC_IMPORT_normaliserSourcePronote_(r.Source_Pronote||'');return !s||s===source;});}catch(e){}
  return {existing:existing,imports:imports,responsables:responsables,classes:EUC_IMPORT_chargerClassesCamin_(),correspondances:EUC_IMPORT_chargerCorrespondances_(annee,source)};
}
function EUC_IMPORT_previsualiserTexteCompletV77(payload){
  EUC_IMPORT_exigerAdminTexte_();payload=payload||{};var texte=String(payload.texte||''),sourceDemandee=EUC_IMPORT_normaliserSourcePronote_(payload.sourcePronote||'AUTO');if(!texte.trim())throw new Error('Aucune donnée Pronote collée.');
  var parsed=EUC_IMPORT_analyserTexteComplet_(texte,{annee:payload.annee});EUC_IMPORT_extraireProfesseursPrincipaux_(texte,parsed);parsed.encoding='COPIER_COLLER_COMPLET';
  var classes=EUC_IMPORT_chargerClassesCamin_(),detection=EUC_IMPORT_detecterSource_(parsed,parsed.annee,classes),source=sourceDemandee==='AUTO'?detection.source:sourceDemandee;if(!source)throw new Error('Source Pronote indéterminée automatiquement. Choisissez LP ou LGT puis relancez l’analyse.');
  parsed.sourcePronote=source;parsed.empreinte=EUC_IMPORT_empreinte_(Utilities.newBlob(source+'\n'+texte,'text/plain').getBytes());
  var d=EUC_IMPORT_chargerDonneesPreviewCompletV77_(parsed.annee,source),corr=EUC_IMPORT_preparerClasses_(parsed,classes,d.correspondances,payload.correspondances||{},payload.classesExclues||[]),offers=classes.filter(function(c){return c.actif;}).map(function(c){return {Code_classe:c.nom,Actif:true,Afficher_formulaire_PFMP:true};}),preview=EUC_IMPORT_previsualiserComplet_(parsed,d.existing,offers,d.imports,d.responsables);
  EUC_IMPORT_enrichirModificationsIdentite_(preview,parsed,source);preview.lignesAnalysees=EUC_IMPORT_construireLignesAnalysees_(preview,parsed,source);
  preview.sourcePronote=source;preview.sourceDemandee=sourceDemandee;preview.sourceDetection=detection;preview.classesCamin=classes.filter(function(c){return c.actif;});preview.classesPronote=corr.classesPronote;preview.classesInconnues=corr.inconnues;preview.classesExclues=corr.exclues;preview.tableCorrespondancePresente=d.correspondances.length>0;preview.correspondancesTemporaires=true;
  preview.compteurs.classesCaminDisponibles=preview.classesCamin.length;preview.compteurs.classesInconnues=corr.inconnues.length;preview.compteurs.classesEcartees=corr.exclues.length;preview.compteurs.elevesEcartes=corr.effectifExclu;preview.compteurs.lignesAffichees=preview.lignesAnalysees.length;preview.compteurs.responsablesLus=parsed.responsablesLus||0;preview.pretAValider=preview.pretAValider&&corr.inconnues.length===0;preview.importComplet=true;return preview;
}
function EUC_IMPORT_confirmerSimulationCompletV77(payload){var lock=LockService.getScriptLock();if(!lock.tryLock(1000))throw new Error('Un autre import est déjà en cours.');try{EUC_IMPORT_exigerAdminTexte_();if(!payload||payload.confirmation!=='CONFIRMER_IMPORT')throw new Error('Validation humaine explicite obligatoire.');var p=EUC_IMPORT_previsualiserTexteCompletV77(payload);if(!p.pretAValider)throw new Error('Prévisualisation bloquée par des anomalies ou classes non correspondantes.');return {statut:'SIMULATION',ecriture:false,sourcePronote:p.sourcePronote,empreinte:p.empreinte,compteurs:p.compteurs};}finally{lock.releaseLock();}}
function EUC_IMPORT_importerReelCompletV77(payload){
  var lock=LockService.getScriptLock();if(!lock.tryLock(3000))throw new Error('Un autre import est déjà en cours.');
  try{
    var ctx=EUC_IMPORT_exigerAdminTexte_();payload=payload||{};if(payload.confirmation!=='IMPORTER_REELLEMENT_DANS_GRIST')throw new Error('Confirmation explicite requise pour l’import réel.');
    var preview=EUC_IMPORT_previsualiserTexteCompletV77(payload);if(!preview.pretAValider)throw new Error('Import réel bloqué : anomalies ou classes inconnues.');var actions=(Number(preview.compteurs.nouveaux)||0)+(Number(preview.compteurs.misesAJour)||0)+(Number(preview.compteurs.reactives)||0);if(actions===0)throw new Error('Import inutile : aucune création ni mise à jour détectée.');
    var source=EUC_IMPORT_normaliserSourcePronote_(preview.sourcePronote||'');if(source!=='LP'&&source!=='LGT')throw new Error('Source Pronote LP/LGT non résolue.');EUC_IMPORT_assurerSchemaRich_();
    var annee=EUC_IMPORT_lireAnnee_(preview.annee),anneeId=annee.id,parsed=EUC_IMPORT_analyserTexteComplet_(String(payload.texte||''),{annee:preview.annee});EUC_IMPORT_extraireProfesseursPrincipaux_(String(payload.texte||''),parsed);
    var classes=EUC_IMPORT_chargerClassesCamin_(),corrPersist=EUC_IMPORT_chargerCorrespondances_(preview.annee,source);EUC_IMPORT_preparerClasses_(parsed,classes,corrPersist,payload.correspondances||{},payload.classesExclues||[]);var classesById={},classesByNom={};classes.forEach(function(c){classesById[String(c.id)]=c;classesByNom[EUC_IMPORT_normaliserCle_(c.nom)]=c;});
    var existing=EUC_IMPORT_lireRecordsBruts_(EUC_IMPORT_ELEVES_TABLE_),idx=EUC_IMPORT_indexExistantsReels_(existing,anneeId,source),posts=[],patches=[],now=EUC_IMPORT_nowGrist_(),lot='PRONOTE-COMPLET-'+source+'-'+preview.annee+'-'+now,seen={};
    parsed.rows.forEach(function(r){if(r._exclueImport||!r.classe||String(r.classe).indexOf('__NON_CORRESPONDUE__')===0)return;var c=classesById[String(r.classeGristId)]||classesByNom[EUC_IMPORT_normaliserCle_(r.classe)];if(!c)return;var stable=EUC_IMPORT_cleStableLigne_(r);if(seen[stable])throw new Error('Doublon détecté : '+r.nom+' '+r.prenom);seen[stable]=true;var cand=idx.stable[stable]||[];if(!cand.length){var ik=[EUC_SUIVI_normaliserIdentite_(r.nom),EUC_SUIVI_normaliserIdentite_(r.prenom),String(r.naissance||'')].join('|');cand=idx.identite[ik]||[];}if(cand.length>1)throw new Error('Rapprochement ambigu : '+r.nom+' '+r.prenom);var common=EUC_IMPORT_recordFieldsRich_(r,c,anneeId,source,stable,preview,now,lot);
      if(cand.length===1){var old=cand[0],f=old.fields||old,diff=EUC_IMPORT_diffObjRich_(f,common).filter(function(k){return ['Date_modification','Identifiant_lot_import','Empreinte_import'].indexOf(k)<0;});if(diff.length){common.Numero_version=(Number(f.Numero_version)||0)+1;patches.push({id:old.id,fields:common});}}
      else{common.Date_creation=now;common.Numero_version=1;posts.push({fields:common});}
    });
    if(posts.length)EUC_ENT_grist('post','/tables/'+encodeURIComponent(EUC_IMPORT_ELEVES_TABLE_)+'/records',{records:posts});if(patches.length)EUC_ENT_grist('patch','/tables/'+encodeURIComponent(EUC_IMPORT_ELEVES_TABLE_)+'/records',{records:patches});
    var reread=EUC_IMPORT_lireRecordsBruts_(EUC_IMPORT_ELEVES_TABLE_),studentIdx=EUC_IMPORT_indexExistantsReels_(reread,anneeId,source),respExisting=EUC_IMPORT_lireRecordsBruts_(EUC_IMPORT_RESP_TABLE_),respByStudentKey={},respPosts=[],respPatches=[];respExisting.forEach(function(rr){var f=rr.fields||{},sid=Number(f.Eleve)||0,key=sid+'|'+String(f.Cle_responsable||'');if(sid&&f.Cle_responsable)respByStudentKey[key]=rr;});
    parsed.rows.forEach(function(r){if(r._exclueImport||!r.classe||String(r.classe).indexOf('__NON_CORRESPONDUE__')===0)return;var stable=EUC_IMPORT_cleStableLigne_(r),cand=studentIdx.stable[stable]||[];if(!cand.length){var ik=[EUC_SUIVI_normaliserIdentite_(r.nom),EUC_SUIVI_normaliserIdentite_(r.prenom),String(r.naissance||'')].join('|');cand=studentIdx.identite[ik]||[];}if(cand.length!==1)return;var sid=cand[0].id;(r.responsables||[]).forEach(function(resp){var nf=EUC_IMPORT_respFieldsRich_(sid,r.ident||'',resp,source,now),key=sid+'|'+nf.Cle_responsable,old=respByStudentKey[key];if(!old)respPosts.push({fields:nf});else if(EUC_IMPORT_diffObjRich_(old.fields||old,nf).filter(function(k){return k!=='Date_derniere_synchro';}).length)respPatches.push({id:old.id,fields:nf});});});
    if(respPosts.length)EUC_ENT_grist('post','/tables/'+encodeURIComponent(EUC_IMPORT_RESP_TABLE_)+'/records',{records:respPosts});if(respPatches.length)EUC_ENT_grist('patch','/tables/'+encodeURIComponent(EUC_IMPORT_RESP_TABLE_)+'/records',{records:respPatches});
    return {ok:true,sourcePronote:source,annee:preview.annee,crees:posts.length,misAJour:patches.length,total:posts.length+patches.length,responsablesCrees:respPosts.length,responsablesMisAJour:respPatches.length,lot:lot,aucuneSuppression:true,auteur:ctx.email||''};
  }finally{lock.releaseLock();}
}
