/** PFMP — DEV449 — sauvegarde apprenti ciblée, sans reconstruction globale. */
var EUC_DEV449_VERSION_='1.0.0-dev.449';
var EUC_DEV449_TABLE_='EUC_APPRENTISSAGE_PFMP';
var EUC_DEV449_COLS_CACHE_='EUC_DEV449_APP_COLS_V1';
function EUC_DEV449_t_(v){return String(v==null?'':v).trim();}
function EUC_DEV449_n_(v){var n=Number(v);return isFinite(n)?n:0;}
function EUC_DEV449_norm_(v){return EUC_DEV449_t_(v).normalize('NFD').replace(/[\u0300-\u036f]/g,'').toUpperCase().replace(/[^A-Z0-9]/g,'');}
function EUC_DEV449_ref_(v){if(Array.isArray(v)){for(var i=0;i<v.length;i++)if(typeof v[i]==='number')return v[i];}return EUC_DEV449_n_(v);}
function EUC_DEV449_cols_(){var cache=CacheService.getScriptCache(),raw='';try{raw=cache.get(EUC_DEV449_COLS_CACHE_)||'';}catch(e){}if(raw){try{return JSON.parse(raw)||[];}catch(e2){}}var cols=(EUC_DEV190_api_('get','/tables/'+encodeURIComponent(EUC_DEV449_TABLE_)+'/columns',null).columns||[]);try{cache.put(EUC_DEV449_COLS_CACHE_,JSON.stringify(cols),21600);}catch(e3){}return cols;}
function EUC_DEV449_col_(cols,names){var wanted=(names||[]).map(EUC_DEV449_norm_);for(var i=0;i<(cols||[]).length;i++)if(wanted.indexOf(EUC_DEV449_norm_(cols[i].id))>=0)return cols[i].id;return'';}
function EUC_DEV449_hash_(s){var h=2166136261,t=String(s||'');for(var i=0;i<t.length;i++){h^=t.charCodeAt(i);h+=(h<<1)+(h<<4)+(h<<7)+(h<<8)+(h<<24);}return(h>>>0).toString(36);}
function EUC_DEV449_episodes_(eleveId,cEleve){var filter={};filter[cEleve]=[eleveId];var path='/tables/'+encodeURIComponent(EUC_DEV449_TABLE_)+'/records?filter='+encodeURIComponent(JSON.stringify(filter));var rows=(EUC_DEV190_api_('get',path,null).records||[]).filter(function(r){return EUC_DEV449_ref_((r.fields||{})[cEleve])===eleveId;});rows.sort(function(a,b){var aa=(a.fields||{}).Actif!==false?1:0,bb=(b.fields||{}).Actif!==false?1:0;return bb-aa||(EUC_DEV449_n_(b.id)-EUC_DEV449_n_(a.id));});return rows;}
function EUC_DEV449_fields_(p,cols){var fields={};function set(names,value){var c=EUC_DEV449_col_(cols,names);if(c)fields[c]=value;}var eleveId=EUC_DEV449_n_(p.eleveId||p.eleve||p.id),siret=EUC_DEV449_t_(p.siret).replace(/\D/g,'').slice(0,14);var full=!!EUC_DEV449_t_(p.dateContrat)&&!!EUC_DEV449_t_(p.debut)&&!!EUC_DEV449_t_(p.fin),rupture=!!EUC_DEV449_t_(p.dateRupture),apprenti=full&&!rupture;set(['Eleve','Élève','Eleve_id'],eleveId);set(['Annee_scolaire'],EUC_DEV449_t_(p.annee));set(['SIRET'],siret);set(['Nom_entreprise'],EUC_DEV449_t_(p.nomEntreprise));set(['Nom_commercial'],EUC_DEV449_t_(p.nomCommercial));set(['Entreprise'],EUC_DEV449_t_(p.nomCommercial||p.nomEntreprise));set(['Adresse_entreprise','Adresse'],EUC_DEV449_t_(p.adresse));set(['Code_postal','CodePostal','CP'],EUC_DEV449_t_(p.cp));set(['Ville'],EUC_DEV449_t_(p.ville));set(['Entreprise_telephone','Telephone_entreprise'],EUC_DEV449_t_(p.telEntreprise));set(['Entreprise_courriel','Courriel_entreprise'],EUC_DEV449_t_(p.mailEntreprise));set(['Responsable_nom','Responsable'],EUC_DEV449_t_(p.responsableEntreprise));set(['Tuteur_nom','Tuteur'],EUC_DEV449_t_(p.tuteur));set(['Tuteur_telephone','Telephone_tuteur'],EUC_DEV449_t_(p.telTuteur));set(['Tuteur_courriel','Courriel_tuteur'],EUC_DEV449_t_(p.mailTuteur));set(['Dossier_distribue'],!!p.dossierDistribue);set(['Date_distribution_dossier'],EUC_DEV449_t_(p.dateDistribution));set(['Dossier_remis'],!!p.dossierRemis);set(['Date_remise_dossier'],EUC_DEV449_t_(p.dateDossier));set(['Dossier_transmis_CFA'],!!p.transmisCfa);set(['Date_transmission_CFA'],EUC_DEV449_t_(p.dateTransmissionCfa||p.dateCfa));set(['Date_contrat_officielle'],EUC_DEV449_t_(p.dateContrat));set(['Date_debut'],EUC_DEV449_t_(p.debut||p.dateContrat));set(['Date_fin'],EUC_DEV449_t_(p.fin));set(['Date_rupture_contrat'],EUC_DEV449_t_(p.dateRupture));set(['Nouveau_contrat'],!!p.nouveauContrat);set(['Statut_dossier'],rupture?'CONTRAT_ROMPU':(full?'CONTRAT_VALIDE':(p.transmisCfa?'TRANSMIS_CFA':(p.dossierRemis?'DOSSIER_REMIS':'A_INITIER'))));set(['Actif'],apprenti);return{fields:fields,apprenti:apprenti,statut:rupture?'SCOLAIRE_RUPTURE':(apprenti?'APPRENTI':((p.dossierRemis||p.transmisCfa)?'FUTUR_APPRENTI':'SCOLAIRE'))};}
function EUC_DEV449_saveApprenti(p){p=p||{};var started=Date.now(),ctx=EUC_V156_contexteAdmin_();if(!ctx)throw new Error('Accès administrateur requis.');if(typeof EUC_DEV424_assertTarget_==='function')EUC_DEV424_assertTarget_();var eleveId=EUC_DEV449_n_(p.eleveId||p.eleve||p.id);if(!eleveId||!EUC_DEV449_t_(p.annee))throw new Error('Élève ou année scolaire invalide.');var fingerprint=EUC_DEV449_hash_(JSON.stringify(p)),dedupeKey='EUC_DEV449_SAVE_'+eleveId+'_'+fingerprint,cache=CacheService.getScriptCache();try{if(cache.get(dedupeKey))return{ok:true,duplicate:true,version:EUC_DEV449_VERSION_,durationMs:Date.now()-started};}catch(e){}var lock=LockService.getScriptLock();if(!lock.tryLock(3000))throw new Error('Une autre sauvegarde est en cours. Réessayez dans quelques secondes.');try{var cols=EUC_DEV449_cols_(),cEleve=EUC_DEV449_col_(cols,['Eleve','Élève','Eleve_id']);if(!cEleve)throw new Error('Colonne Élève introuvable.');var rows=EUC_DEV449_episodes_(eleveId,cEleve),prepared=EUC_DEV449_fields_(p,cols),created=false,rowId=0;if(p.nouveauContrat||!rows.length){var added=EUC_DEV190_api_('post','/tables/'+encodeURIComponent(EUC_DEV449_TABLE_)+'/records',{records:[{fields:prepared.fields}]});rowId=EUC_DEV449_n_(added&&added.records&&added.records[0]&&added.records[0].id);created=true;}else{rowId=EUC_DEV449_n_(rows[0].id);EUC_DEV190_api_('patch','/tables/'+encodeURIComponent(EUC_DEV449_TABLE_)+'/records',{records:[{id:rowId,fields:prepared.fields}]});}try{cache.put(dedupeKey,'1',60);}catch(e2){}try{if(typeof EUC_DEV396_invalidateAppSnapshots_==='function')EUC_DEV396_invalidateAppSnapshots_(p.annee);}catch(e3){}return{ok:true,version:EUC_DEV449_VERSION_,rowId:rowId,created:created,apprenti:prepared.apprenti,statut:prepared.statut,durationMs:Date.now()-started,gristCallsEstimate:3};}finally{lock.releaseLock();}}
