/** Eucalyptus PFMP — v1.0.0-dev.112 — QR référence + clé d’accès Grist + contrôle naissance. */
function EUC_CONVENTION_lireAccesFraisV108_(){var raw=EUC_ENT_grist('get','/tables/'+encodeURIComponent(EUC_CONVENTION_ACCES_TABLE_)+'/records');return (raw.records||[]).map(function(r){var o={id:r.id},f=r.fields||{};Object.keys(f).forEach(function(k){o[k]=f[k];});return o;});}
function EUC_CONVENTION_resoudreLienV112_(code,cle){code=String(code||'').trim();cle=String(cle||'').trim();try{code=decodeURIComponent(code);}catch(e){}try{cle=decodeURIComponent(cle);}catch(e2){}if(!code||!cle)throw new Error('[QR112-ENTREE] Paramètres QR incomplets : référence='+(code?1:0)+', clé='+(cle?1:0)+'.');var rows;try{rows=EUC_CONVENTION_lireAccesFraisV108_();}catch(err){throw new Error('[QR112-GRIST] Lecture de la table d’accès impossible : '+(err&&err.message?err.message:String(err)));}var refRows=rows.filter(function(r){return String(r.Reference_convention||'').trim()===code;}),keyRows=rows.filter(function(r){return String(r.Token_hash||'').trim()===cle;}),matches=rows.filter(function(r){return r.Revoked!==true&&String(r.Reference_convention||'').trim()===code&&String(r.Token_hash||'').trim()===cle;});if(matches.length!==1)throw new Error('[QR112-LIEN] Diagnostic : lignes='+rows.length+', référence='+refRows.length+', clé='+keyRows.length+', couple='+matches.length+', clé8='+cle.substring(0,8)+'.');var a=matches[0];return {acces:a,mode:'REFERENCE_CLE',diag:'QR112-LIEN-OK id='+a.id};}
function EUC_CONVENTION_verifierNaissanceV112_(resolved,jour,mois){var a=resolved.acces;jour=Number(jour||0);mois=Number(mois||0);if(jour<1||jour>31||mois<1||mois>12)throw new Error('[QR112-NAISSANCE] Jour ou mois invalide.');var eleves;try{eleves=EUC_IMPORT_lireRecords_('EUC_ELEVES_PFMP');}catch(e){throw new Error('[QR112-ELEVES] Lecture de la table élèves impossible : '+(e&&e.message?e.message:String(e)));}var ref=Number(EUC_PFMP_ref_(a.Eleve)),el=eleves.filter(function(x){return Number(x.id)===ref;})[0];if(!el)throw new Error('[QR112-ELEVE] Élève '+ref+' introuvable.');var iso=EUC_IMPORT_dateExistanteISO_(el.Date_naissance),parts=String(iso||'').split('-');if(parts.length!==3)throw new Error('[QR112-DATE] Date de naissance illisible pour l’élève '+ref+'.');if(Number(parts[2])!==jour||Number(parts[1])!==mois)throw new Error('[QR112-NAISSANCE] Lien valide, mais jour/mois ne correspondent pas à la date enregistrée.');EUC_ENT_grist('patch','/tables/'+encodeURIComponent(EUC_CONVENTION_ACCES_TABLE_)+'/records',{records:[{id:a.id,fields:{Tentatives_echec:0,Bloque_jusqua:null,Date_derniere_utilisation:new Date().toISOString(),Statut:'FORMULAIRE_OUVERT'}}]});return {ok:true,diagnostic:resolved.diag+' - NAISSANCE-OK',reference:a.Reference_convention||'',eleve:{nom:el.Nom||'',prenom:el.Prenom_usage||el.Prenom||'',classeConvention:a.Classe_convention_nom||el.Code_classe_importe||el.Classe_nom||'',anneeConvention:a.Annee_scolaire||el.Annee_scolaire_code||el.Annee_scolaire||'',dateDebut:a.Date_debut?EUC_CONVENTION_dateFRV85_(EUC_IMPORT_dateExistanteISO_(a.Date_debut),true):'',dateFin:a.Date_fin?EUC_CONVENTION_dateFRV85_(EUC_IMPORT_dateExistanteISO_(a.Date_fin),true):''}};}
function EUC_CONVENTION_verifierIdentiteV112(code,cle,jour,mois){return EUC_CONVENTION_verifierNaissanceV112_(EUC_CONVENTION_resoudreLienV112_(code,cle),jour,mois);}
function EUC_CONVENTION_verifierIdentiteV111(code,token,jour,mois){return EUC_CONVENTION_verifierIdentiteV112(code,EUC_CONVENTION_hash_(String(token||'')),jour,mois);}
function EUC_CONVENTION_verifierIdentiteV110(code,token,sig,jour,mois){return EUC_CONVENTION_verifierIdentiteV111(code,token,jour,mois);}
function EUC_CONVENTION_verifierIdentiteV108(aid,code,eid,token,sig,jour,mois){return EUC_CONVENTION_verifierIdentiteV111(code,token,jour,mois);}
function EUC_CONVENTION_verifierIdentiteV107(code,token,jour,mois){return EUC_CONVENTION_verifierIdentiteV111(code,token,jour,mois);}
function EUC_CONVENTION_verifierIdentiteV106(code,token,jour,mois){return EUC_CONVENTION_verifierIdentiteV111(code,token,jour,mois);}
