/** Eucalyptus PFMP — v1.0.0-dev.94 — DOCX maître, QR court, lots optimisés et document unique imprimable. */
var EUC_DOCX_TEMPLATE_PROP_='EUC_PFMP_DOCX_TEMPLATE_ID';
var EUC_DOCX_ROOT_FOLDER_='Eucalyptus PFMP';
var EUC_DOCX_MODEL_FOLDER_='Modeles';
var EUC_DOCX_OUTPUT_FOLDER_='Conventions';
var EUC_DOCX_TEMPLATE_NAME_='Convention_PFMP_MODELE.docx';
var EUC_DOCX_MIME_='application/vnd.openxmlformats-officedocument.wordprocessingml.document';
function EUC_DOCX_exigerAdmin_(){var ctx=EUC_PFMP_contexteAdmin_();if(!ctx||!ctx.autorise)throw new Error('Accès administrateur requis.');return ctx;}
function EUC_DOCX_folder_(parent,name){var it=parent.getFoldersByName(name);return it.hasNext()?it.next():parent.createFolder(name);}
function EUC_DOCX_root_(){return EUC_DOCX_folder_(DriveApp.getRootFolder(),EUC_DOCX_ROOT_FOLDER_);}
function EUC_DOCX_modelFolder_(){return EUC_DOCX_folder_(EUC_DOCX_root_(),EUC_DOCX_MODEL_FOLDER_);}
function EUC_DOCX_outputRoot_(){return EUC_DOCX_folder_(EUC_DOCX_root_(),EUC_DOCX_OUTPUT_FOLDER_);}
function EUC_DOCX_safeName_(v){return String(v||'').trim().replace(/[\\/:*?"<>|]+/g,'-').replace(/\s+/g,' ').substring(0,90)||'Sans_nom';}
function EUC_DOCX_fileByProp_(){var id=PropertiesService.getScriptProperties().getProperty(EUC_DOCX_TEMPLATE_PROP_);if(!id)return null;try{var f=DriveApp.getFileById(id);return f.isTrashed()?null:f;}catch(e){return null;}}
function EUC_DOCX_modeleInfo(){EUC_DOCX_exigerAdmin_();var f=EUC_DOCX_fileByProp_(),base='Mon Drive / '+EUC_DOCX_ROOT_FOLDER_+' / '+EUC_DOCX_MODEL_FOLDER_;if(!f)return {configure:false,emplacement:base,nom:'',url:'',id:''};return {configure:true,id:f.getId(),nom:f.getName(),url:f.getUrl(),taille:f.getSize(),maj:f.getLastUpdated().toISOString(),emplacement:base+' / '+f.getName()};}
function EUC_DOCX_importerModele(payload){EUC_DOCX_exigerAdmin_();payload=payload||{};var name=EUC_DOCX_safeName_(payload.nom||EUC_DOCX_TEMPLATE_NAME_);if(!/\.docx$/i.test(name))name+='.docx';var b64=String(payload.base64||'').replace(/^data:[^,]+,/, '');if(!b64)throw new Error('Fichier Word manquant.');var bytes=Utilities.base64Decode(b64);if(bytes.length<1000)throw new Error('Le fichier DOCX paraît vide ou invalide.');if(bytes.length>5*1024*1024)throw new Error('Le modèle DOCX dépasse 5 Mo.');var folder=EUC_DOCX_modelFolder_(),old=EUC_DOCX_fileByProp_();if(old){try{old.setName('ARCHIVE_'+Utilities.formatDate(new Date(),Session.getScriptTimeZone()||'Europe/Paris','yyyyMMdd_HHmmss')+'_'+old.getName());}catch(e){}}var f=folder.createFile(Utilities.newBlob(bytes,EUC_DOCX_MIME_,name));PropertiesService.getScriptProperties().setProperty(EUC_DOCX_TEMPLATE_PROP_,f.getId());return EUC_DOCX_modeleInfo();}
function EUC_DOCX_xmlEscape_(v){return String(v===null||v===undefined?'':v).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&apos;');}
function EUC_DOCX_replaceAll_(text,map){Object.keys(map).forEach(function(k){text=text.split(k).join(EUC_DOCX_xmlEscape_(map[k]));});return text;}
function EUC_DOCX_qrUrl_(url){return 'https://quickchart.io/qr?size=420&margin=2&ecLevel=Q&text='+encodeURIComponent(String(url||''));}
function EUC_DOCX_qrBlob_(url,name){var r=UrlFetchApp.fetch(EUC_DOCX_qrUrl_(url),{muteHttpExceptions:true,followRedirects:true});if(r.getResponseCode()<200||r.getResponseCode()>=300)throw new Error('Impossible de générer le QR code ('+r.getResponseCode()+').');return r.getBlob().setName(name||'word/media/image1.png');}
function EUC_DOCX_destination_(data){var y=EUC_DOCX_folder_(EUC_DOCX_outputRoot_(),EUC_DOCX_safeName_(data.annee||'Annee'));return EUC_DOCX_folder_(y,EUC_DOCX_safeName_(data.classe||'Classe'));}
function EUC_DOCX_map_(data){return {'{{DATE_DEBUT}}':data.debutCourt||data.debut||'','{{DATE_FIN}}':data.finCourt||data.fin||'','{{JOURS}}':data.jours||0,'{{CLASSE}}':data.classe||'','{{NOM_ELEVE}}':data.eleve.nom||'','{{PRENOM_ELEVE}}':data.eleve.prenom||'','{{DATE_NAISSANCE}}':data.eleve.dateNaissance||'','{{ADRESSE_ELEVE}}':data.eleve.adresse||'','{{CP_VILLE_ELEVE}}':[data.eleve.codePostal||'',data.eleve.ville||''].join(' ').trim(),'{{TEL_ELEVE}}':data.eleve.telephone||'','{{EMAIL_ELEVE}}':data.eleve.courriel||'','{{DIPLOME}}':data.diplome||data.eleve.formation||'','{{ETABLISSEMENT}}':data.etablissement.libelle||'','{{ADRESSE_ETABLISSEMENT}}':data.etablissement.adresse||'','{{TEL_ETABLISSEMENT}}':data.etablissement.telephone||'','{{PROVISEUR}}':data.etablissement.proviseur||'','{{FONCTION_PROVISEUR}}':data.etablissement.fonctionProviseur||'','{{EMAIL_ETABLISSEMENT}}':data.etablissement.email||'','{{PROF_REFERENT}}':data.professeurReferent||'','{{EMAIL_PROF}}':data.professeurReferentEmail||'','{{REFERENCE}}':data.reference||''};}
function EUC_DOCX_prepareTemplate_(){var tpl=EUC_DOCX_fileByProp_();if(!tpl)throw new Error('Aucun modèle Word actif. Ouvrez « Paramètres de la convention » et installez le modèle DOCX maître.');var sourceZip=Utilities.newBlob(tpl.getBlob().getBytes(),'application/zip','modele.zip'),parts=Utilities.unzip(sourceZip),by={};parts.forEach(function(b){by[b.getName()]=b;});if(!by['word/document.xml'])throw new Error('Modèle DOCX invalide : word/document.xml introuvable.');if(!by['word/media/image1.png'])throw new Error('Modèle DOCX invalide : emplacement QR introuvable.');return {parts:parts,by:by};}
function EUC_DOCX_buildOne_(prep,data,qrBlob,filename){var out=[];prep.parts.forEach(function(b){var n=b.getName();if(n==='word/document.xml')out.push(Utilities.newBlob(EUC_DOCX_replaceAll_(b.getDataAsString('UTF-8'),EUC_DOCX_map_(data)),'application/xml',n));else if(n==='word/media/image1.png')out.push(qrBlob.copyBlob().setName(n));else out.push(b.copyBlob());});var zipBlob=Utilities.zip(out,'archive.zip');return Utilities.newBlob(zipBlob.getBytes(),EUC_DOCX_MIME_,filename);}
function EUC_DOCX_genererDepuisToken(token){EUC_DOCX_exigerAdmin_();token=String(token||'').trim();if(!token)throw new Error('Jeton de convention manquant.');EUC_CONVENTION_resetCacheV94_();var data=EUC_CONVENTION_donneesImpressionV80(token),prep=EUC_DOCX_prepareTemplate_(),qr=EUC_DOCX_qrBlob_(data.formUrl,'word/media/image1.png'),filename='Convention_'+EUC_DOCX_safeName_(data.eleve.nom)+'_'+EUC_DOCX_safeName_(data.eleve.prenom)+'_'+EUC_DOCX_safeName_(data.reference)+'.docx',folder=EUC_DOCX_destination_(data),old=folder.getFilesByName(filename);while(old.hasNext())old.next().setTrashed(true);var f=folder.createFile(EUC_DOCX_buildOne_(prep,data,qr,filename));return {ok:true,id:f.getId(),nom:f.getName(),url:f.getUrl(),folderUrl:folder.getUrl(),emplacement:'Mon Drive / '+EUC_DOCX_ROOT_FOLDER_+' / '+EUC_DOCX_OUTPUT_FOLDER_+' / '+EUC_DOCX_safeName_(data.annee)+' / '+EUC_DOCX_safeName_(data.classe),reference:data.reference};}
function EUC_DOCX_fetchQrsV94_(datas){var req=datas.map(function(d){return {url:EUC_DOCX_qrUrl_(d.formUrl),muteHttpExceptions:true,followRedirects:true};}),res=UrlFetchApp.fetchAll(req);return res.map(function(r,i){if(r.getResponseCode()<200||r.getResponseCode()>=300)throw new Error('Impossible de générer le QR '+(i+1)+' ('+r.getResponseCode()+').');return r.getBlob();});}
function EUC_DOCX_genererLot(tokens){EUC_DOCX_exigerAdmin_();tokens=(tokens||[]).map(String).filter(Boolean);if(!tokens.length)throw new Error('Aucune convention à générer.');if(tokens.length>80)throw new Error('Lot trop important : maximum 80 conventions par génération.');EUC_CONVENTION_resetCacheV94_();var datas=tokens.map(function(t){return EUC_CONVENTION_donneesImpressionV80(t);}),prep=EUC_DOCX_prepareTemplate_(),qrs=EUC_DOCX_fetchQrsV94_(datas),folder=EUC_DOCX_destination_(datas[0]),items=[];datas.forEach(function(data,i){var filename='Convention_'+EUC_DOCX_safeName_(data.eleve.nom)+'_'+EUC_DOCX_safeName_(data.eleve.prenom)+'_'+EUC_DOCX_safeName_(data.reference)+'.docx',old=folder.getFilesByName(filename);while(old.hasNext())old.next().setTrashed(true);var f=folder.createFile(EUC_DOCX_buildOne_(prep,data,qrs[i],'word/media/image1.png',filename));items.push({ok:true,id:f.getId(),nom:f.getName(),url:f.getUrl(),folderUrl:folder.getUrl(),reference:data.reference});});return {ok:true,total:items.length,items:items,folderUrl:folder.getUrl(),dureeOptimisee:true};}
function EUC_DOCX_genererLotImprimableV94(tokens){
  EUC_DOCX_exigerAdmin_();tokens=(tokens||[]).map(String).filter(Boolean);if(!tokens.length)throw new Error('Aucune convention à générer.');if(tokens.length>40)throw new Error('Lot imprimable limité à 40 conventions.');EUC_CONVENTION_resetCacheV94_();var datas=tokens.map(function(t){return EUC_CONVENTION_donneesImpressionV80(t);}),prep=EUC_DOCX_prepareTemplate_(),doc=prep.by['word/document.xml'].getDataAsString('UTF-8'),relsBlob=prep.by['word/_rels/document.xml.rels'];if(!relsBlob)throw new Error('Modèle DOCX invalide : relations document introuvables.');var rels=relsBlob.getDataAsString('UTF-8'),bodyMatch=doc.match(/<w:body>([\s\S]*?)<\/w:body>/);if(!bodyMatch)throw new Error('Modèle DOCX invalide : corps Word introuvable.');var body=bodyMatch[1],sect='',sm=body.match(/(<w:sectPr[\s\S]*?<\/w:sectPr>)\s*$/);if(sm){sect=sm[1];body=body.slice(0,sm.index);}var rm=rels.match(/<Relationship[^>]+Id="([^"]+)"[^>]+Target="media\/image1\.png"[^>]*\/>/);if(!rm)throw new Error('Modèle DOCX invalide : relation du QR introuvable.');var baseRid=rm[1],qrs=EUC_DOCX_fetchQrsV94_(datas),bodies=[],newRels=[];datas.forEach(function(data,i){var rid=i===0?baseRid:'rIdEUCQR'+(i+1),chunk=EUC_DOCX_replaceAll_(body,EUC_DOCX_map_(data));if(i>0)chunk=chunk.split('r:embed="'+baseRid+'"').join('r:embed="'+rid+'"');bodies.push(chunk);if(i<datas.length-1)bodies.push('<w:p><w:r><w:br w:type="page"/></w:r></w:p>');if(i>0)newRels.push('<Relationship Id="'+rid+'" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/image" Target="media/qr_'+(i+1)+'.png"/>');});var merged=doc.replace(bodyMatch[0],'<w:body>'+bodies.join('')+sect+'</w:body>');if(newRels.length)rels=rels.replace('</Relationships>',newRels.join('')+'</Relationships>');var out=[];prep.parts.forEach(function(b){var n=b.getName();if(n==='word/document.xml')out.push(Utilities.newBlob(merged,'application/xml',n));else if(n==='word/_rels/document.xml.rels')out.push(Utilities.newBlob(rels,'application/xml',n));else if(n==='word/media/image1.png')out.push(qrs[0].copyBlob().setName(n));else out.push(b.copyBlob());});for(var i=1;i<qrs.length;i++)out.push(qrs[i].copyBlob().setName('word/media/qr_'+(i+1)+'.png'));var filename='LOT_'+EUC_DOCX_safeName_(datas[0].classe)+'_'+EUC_DOCX_safeName_(datas[0].annee)+'_'+datas.length+'_conventions.docx',folder=EUC_DOCX_destination_(datas[0]),old=folder.getFilesByName(filename);while(old.hasNext())old.next().setTrashed(true);var zipBlob=Utilities.zip(out,'archive.zip'),f=folder.createFile(Utilities.newBlob(zipBlob.getBytes(),EUC_DOCX_MIME_,filename));return {ok:true,total:datas.length,id:f.getId(),nom:f.getName(),url:f.getUrl(),folderUrl:folder.getUrl(),reference:'LOT',type:'DOCX_LOT_UNIQUE'};
}
