/** Eucalyptus PFMP — v1.0.0-dev.104 — PDF maître ancré robuste + QR par référence persistante exacte. */
var EUC_PDF_TEMPLATE_PROP_='EUC_PFMP_PDF_TEMPLATE_ID';
var EUC_PDF_TEMPLATE_NAME_='Convention_PFMP_MODELE.pdf';
var EUC_PDF_MIME_='application/pdf';
function EUC_PDF_exigerAdmin_(){var ctx=EUC_PFMP_contexteAdmin_();if(!ctx||!ctx.autorise)throw new Error('Accès administrateur requis.');return ctx;}
function EUC_dispatchUploadV95(type,payload){type=String(type||'').toUpperCase();if(type==='DOCX')return EUC_DOCX_importerModele(payload);if(type==='PDF')return EUC_PDF_importerModele(payload);throw new Error('Type de modèle inconnu.');}
function EUC_PDF_fileByProp_(){var id=PropertiesService.getScriptProperties().getProperty(EUC_PDF_TEMPLATE_PROP_);if(!id)return null;try{var f=DriveApp.getFileById(id);return f.isTrashed()?null:f;}catch(e){return null;}}
function EUC_PDF_modeleInfo(){EUC_PDF_exigerAdmin_();var f=EUC_PDF_fileByProp_(),base='Mon Drive / Eucalyptus PFMP / Modeles';if(!f)return {configure:false,emplacement:base,nom:'',url:'',id:''};return {configure:true,id:f.getId(),nom:f.getName(),url:f.getUrl(),taille:f.getSize(),maj:f.getLastUpdated().toISOString(),emplacement:base+' / '+f.getName()};}
function EUC_PDF_importerModele(payload){EUC_PDF_exigerAdmin_();payload=payload||{};var name=EUC_DOCX_safeName_(payload.nom||EUC_PDF_TEMPLATE_NAME_);if(!/\.pdf$/i.test(name))name+='.pdf';var b64=String(payload.base64||'').replace(/^data:[^,]+,/, '');if(!b64)throw new Error('Fichier PDF manquant.');var bytes=Utilities.base64Decode(b64);if(bytes.length<1000)throw new Error('Le PDF paraît vide ou invalide.');if(bytes.length>8*1024*1024)throw new Error('Le modèle PDF dépasse 8 Mo.');var folder=EUC_DOCX_modelFolder_(),old=EUC_PDF_fileByProp_();if(old)old.setTrashed(true);var f=folder.createFile(Utilities.newBlob(bytes,EUC_PDF_MIME_,name));PropertiesService.getScriptProperties().setProperty(EUC_PDF_TEMPLATE_PROP_,f.getId());CacheService.getScriptCache().remove('EUC_PFMP_PDF_MASTER_B64');return EUC_PDF_modeleInfo();}
function EUC_PDF_modeleBase64_(){var cache=CacheService.getScriptCache(),key='EUC_PFMP_PDF_MASTER_B64',cached=cache.get(key);if(cached)return cached;var f=EUC_PDF_fileByProp_();if(!f)throw new Error('Aucun modèle PDF actif. Ouvrez « Paramètres de la convention » et installez le PDF maître 2 pages.');var b64=Utilities.base64Encode(f.getBlob().getBytes());try{cache.put(key,b64,21600);}catch(e){}return b64;}
function EUC_PDF_urlReferenceV104_(reference){return ScriptApp.getService().getUrl()+'?page=pfmp&q='+encodeURIComponent(String(reference||''));}
function EUC_PDF_preparerDataV104_(data){data.formUrl=EUC_PDF_urlReferenceV104_(data.reference);return data;}
function EUC_PDF_payloadTokenV95(token){EUC_PDF_exigerAdmin_();EUC_CONVENTION_resetCacheV94_();var data=EUC_PDF_preparerDataV104_(EUC_CONVENTION_donneesImpressionV80(String(token||'')));if(!data.reference)throw new Error('Référence de convention absente : QR impossible.');return {version:'Eucalyptus PFMP — v1.0.0-dev.104',mode:'single',pdfBase64:EUC_PDF_modeleBase64_(),items:[data],filename:'Convention_'+EUC_DOCX_safeName_(data.eleve.nom)+'_'+EUC_DOCX_safeName_(data.eleve.prenom)+'_'+EUC_DOCX_safeName_(data.reference)+'.pdf'};}
function EUC_PDF_payloadLotV95(lot){EUC_PDF_exigerAdmin_();var d=EUC_CONVENTION_donneesImpressionLot(String(lot||'')),tokens=(d.items||[]).map(function(i){return i.token;}).filter(Boolean);if(!tokens.length)throw new Error('Aucune convention dans ce lot.');if(tokens.length>40)throw new Error('Lot PDF limité à 40 conventions.');EUC_CONVENTION_resetCacheV94_();var datas=tokens.map(function(t){var x=EUC_PDF_preparerDataV104_(EUC_CONVENTION_donneesImpressionV80(t));if(!x.reference)throw new Error('Référence absente dans le lot.');return x;});return {version:'Eucalyptus PFMP — v1.0.0-dev.104',mode:'batch',pdfBase64:EUC_PDF_modeleBase64_(),items:datas,filename:'LOT_'+EUC_DOCX_safeName_(d.classe||datas[0].classe)+'_'+EUC_DOCX_safeName_(d.annee||datas[0].annee)+'_'+datas.length+'_conventions.pdf'};}
