/** Eucalyptus PFMP — v1.0.0-dev.109 — PDF vierge intact + lignes riches coordonnées + QR signé. */
var EUC_PDF_TEMPLATE_PROP_='EUC_PFMP_PDF_TEMPLATE_ID';
var EUC_PDF_TEMPLATE_NAME_='Convention_PFMP_MODELE.pdf';
var EUC_PDF_MIME_='application/pdf';
function EUC_PDF_exigerAdmin_(){var ctx=EUC_PFMP_contexteAdmin_();if(!ctx||!ctx.autorise)throw new Error('Accès administrateur requis.');return ctx;}
function EUC_dispatchUploadV95(type,payload){type=String(type||'').toUpperCase();if(type==='DOCX')return EUC_DOCX_importerModele(payload);if(type==='PDF')return EUC_PDF_importerModele(payload);throw new Error('Type de modèle inconnu.');}
function EUC_PDF_fileByProp_(){var id=PropertiesService.getScriptProperties().getProperty(EUC_PDF_TEMPLATE_PROP_);if(!id)return null;try{var f=DriveApp.getFileById(id);return f.isTrashed()?null:f;}catch(e){return null;}}
function EUC_PDF_modeleInfo(){EUC_PDF_exigerAdmin_();var f=EUC_PDF_fileByProp_(),base='Mon Drive / Eucalyptus PFMP / Modeles';if(!f)return {configure:false,emplacement:base,nom:'',url:'',id:''};return {configure:true,id:f.getId(),nom:f.getName(),url:f.getUrl(),taille:f.getSize(),maj:f.getLastUpdated().toISOString(),emplacement:base+' / '+f.getName()};}
function EUC_PDF_importerModele(payload){EUC_PDF_exigerAdmin_();payload=payload||{};var name=EUC_DOCX_safeName_(payload.nom||EUC_PDF_TEMPLATE_NAME_);if(!/\.pdf$/i.test(name))name+='.pdf';var b64=String(payload.base64||'').replace(/^data:[^,]+,/, '');if(!b64)throw new Error('Fichier PDF manquant.');var bytes=Utilities.base64Decode(b64);if(bytes.length<1000)throw new Error('Le PDF paraît vide ou invalide.');if(bytes.length>8*1024*1024)throw new Error('Le modèle PDF dépasse 8 Mo.');var folder=EUC_DOCX_modelFolder_(),old=EUC_PDF_fileByProp_();if(old)old.setTrashed(true);var f=folder.createFile(Utilities.newBlob(bytes,EUC_PDF_MIME_,name));PropertiesService.getScriptProperties().setProperty(EUC_PDF_TEMPLATE_PROP_,f.getId());CacheService.getScriptCache().remove('EUC_PFMP_PDF_MASTER_B64');return EUC_PDF_modeleInfo();}
function EUC_PDF_modeleBase64_(){var cache=CacheService.getScriptCache(),key='EUC_PFMP_PDF_MASTER_B64',cached=cache.get(key);if(cached)return cached;var f=EUC_PDF_fileByProp_();if(!f)throw new Error('Aucun modèle PDF actif. Installez le patron PDF vierge 2 pages.');var b64=Utilities.base64Encode(f.getBlob().getBytes());try{cache.put(key,b64,21600);}catch(e){}return b64;}
function EUC_PDF_lireAccesFraisV108_(){var raw=EUC_ENT_grist('get','/tables/'+encodeURIComponent(EUC_CONVENTION_ACCES_TABLE_)+'/records');return (raw.records||[]).map(function(r){var o={id:r.id},f=r.fields||{};Object.keys(f).forEach(function(k){o[k]=f[k];});return o;});}
function EUC_CONVENTION_qrSecretV108_(){var p=PropertiesService.getScriptProperties(),k='EUC_PFMP_QR_HMAC_SECRET',s=p.getProperty(k);if(!s){s=[Utilities.getUuid(),Utilities.getUuid(),Utilities.getUuid()].join('|');p.setProperty(k,s);}return s;}
function EUC_CONVENTION_qrSignatureV108_(accessId,ref,eleveId,token){var data=[String(accessId||''),String(ref||''),String(eleveId||''),EUC_CONVENTION_hash_(String(token||''))].join('|');return Utilities.base64EncodeWebSafe(Utilities.computeHmacSha256Signature(data,EUC_CONVENTION_qrSecretV108_())).replace(/=+$/,'');}
function EUC_PDF_preparerDataV109_(data,rows,modeles){var token=String(data&&data.token||'').trim(),ref=String(data&&data.reference||'').trim();if(!token||!ref)throw new Error('Jeton ou référence de convention absent : QR impossible.');var h=EUC_CONVENTION_hash_(token),matches=(rows||[]).filter(function(r){return r.Revoked!==true&&String(r.Token_hash||'')===h&&String(r.Reference_convention||'').trim()===ref;});if(matches.length!==1)throw new Error('Contrôle QR impossible : le couple référence/jeton n’est pas retrouvé de façon unique dans Grist.');var a=matches[0],aid=Number(a.id||0),eid=Number(EUC_PFMP_ref_(a.Eleve)||0);if(!aid||!eid)throw new Error('Contrôle QR impossible : identifiant accès ou élève absent.');data.diplome=EUC_CONVENTION_diplomeStrictV108_(data.classeId);var sig=EUC_CONVENTION_qrSignatureV108_(aid,ref,eid,token),base=ScriptApp.getService().getUrl();data.accessId=aid;data.eleveIdQr=eid;data.qrSignature=sig;data.formUrl=base+'?page=pfmp&aid='+encodeURIComponent(aid)+'&q='+encodeURIComponent(ref)+'&eid='+encodeURIComponent(eid)+'&token='+encodeURIComponent(token)+'&sig='+encodeURIComponent(sig);data.qrReference=ref;data.lignes=EUC_CONVENTION_rendreLignesV108_(data,modeles);return data;}
function EUC_PDF_payloadTokenV95(token){EUC_PDF_exigerAdmin_();EUC_CONVENTION_resetCacheV94_();var modeles=EUC_CONVENTION_lireModelesLignesV108_(),data=EUC_CONVENTION_donneesImpressionV80(String(token||'')),rows=EUC_PDF_lireAccesFraisV108_();data=EUC_PDF_preparerDataV109_(data,rows,modeles);return {version:'Eucalyptus PFMP — v1.0.0-dev.109',mode:'single',pdfBase64:EUC_PDF_modeleBase64_(),items:[data],filename:'Convention_'+EUC_DOCX_safeName_(data.eleve.nom)+'_'+EUC_DOCX_safeName_(data.eleve.prenom)+'_'+EUC_DOCX_safeName_(data.reference)+'.pdf'};}
function EUC_PDF_payloadLotV95(lot){EUC_PDF_exigerAdmin_();var d=EUC_CONVENTION_donneesImpressionLot(String(lot||'')),tokens=(d.items||[]).map(function(i){return i.token;}).filter(Boolean);if(!tokens.length)throw new Error('Aucune convention dans ce lot.');if(tokens.length>40)throw new Error('Lot PDF limité à 40 conventions.');EUC_CONVENTION_resetCacheV94_();var modeles=EUC_CONVENTION_lireModelesLignesV108_(),rows=EUC_PDF_lireAccesFraisV108_(),datas=tokens.map(function(t){return EUC_PDF_preparerDataV109_(EUC_CONVENTION_donneesImpressionV80(t),rows,modeles);});return {version:'Eucalyptus PFMP — v1.0.0-dev.109',mode:'batch',pdfBase64:EUC_PDF_modeleBase64_(),items:datas,filename:'LOT_'+EUC_DOCX_safeName_(d.classe||datas[0].classe)+'_'+EUC_DOCX_safeName_(d.annee||datas[0].annee)+'_'+datas.length+'_conventions.pdf'};}
/* Compatibilité interne avec appels DEV.108 éventuels. */
function EUC_PDF_preparerDataV108_(data,rows,modeles){return EUC_PDF_preparerDataV109_(data,rows,modeles);}
