/** Eucalyptus PFMP — v1.0.0-dev.28 — services de recette, écritures simulées. */
var EUC_PFMP_SUBMISSION_COLUMNS = [
  'Reference','Date_creation','Date_modification','Annee_scolaire','Annee_libelle_snapshot','Statut_jeune','Diplome','Diplome_snapshot','Classe','Classe_snapshot','Offre_formation','Periode_officielle','Periode_snapshot','Date_officielle_debut','Date_officielle_fin','Dates_conformes','Scenario_dates','Date_declaree_debut','Date_declaree_fin','Motif','Commentaire_jeune','Jeune_nom','Jeune_prenom','Jeune_date_naissance','Jeune_telephone','Jeune_courriel','Jeune_adresse','Jeune_complement_adresse','Jeune_code_postal','Jeune_commune','Entreprise','Entreprise_siret_snapshot','Entreprise_raison_sociale_snapshot','Entreprise_enseigne_snapshot','Entreprise_nom_usage_snapshot','Entreprise_adresse_snapshot','Entreprise_commune_snapshot','Entreprise_confirmee','Entreprise_telephone_snapshot','Entreprise_courriel_snapshot','Contact_entreprise','Responsable_nom','Responsable_fonction','Responsable_telephone','Responsable_courriel','Tuteur_nom','Tuteur_fonction','Tuteur_telephone','Tuteur_courriel','Statut_administratif','Valide_par','Date_validation','Commentaire_administratif','Etat_courriel_admin','Date_courriel_admin','Erreur_courriel_admin','Etat_courriel_jeune','Empreinte_doublon','Nonce_hash','Auteur_technique','Version_formulaire','Entreprise_complement_adresse_snapshot','Entreprise_code_postal_snapshot','Entreprise_pays_snapshot'
];

function EUC_PFMP_lireTable_(table) { var r=EUC_ENT_grist('get','/tables/'+encodeURIComponent(table)+'/records'); return r.records||[]; }
function EUC_PFMP_ref_(v) { return Array.isArray(v)?Number(v[0]||0):Number(v||0); }
function EUC_PFMP_dateIso_(v) { if(!v)return ''; if(typeof v==='number')return new Date(v*1000).toISOString().slice(0,10); return String(v).slice(0,10); }
function EUC_PFMP_chargerReferentiel() {
  EUC_ENT_controlerAccesUtilisateur_(); EUC_ENT_controlerCibleRecette_();
  var annees=EUC_PFMP_lireTable_(EUC_PFMP_TABLES.annees).filter(function(r){return r.fields.Active===true;});
  var diplomes=EUC_PFMP_lireTable_(EUC_PFMP_TABLES.diplomes), classes=EUC_PFMP_lireTable_('Classes');
  var offres=EUC_PFMP_lireTable_(EUC_PFMP_TABLES.offres).filter(function(r){return r.fields.Actif===true&&r.fields.Afficher_formulaire_PFMP===true;});
  var relations=EUC_PFMP_lireTable_(EUC_PFMP_TABLES.relations).filter(function(r){return r.fields.Active===true;});
  var periodes=EUC_PFMP_lireTable_(EUC_PFMP_TABLES.periodes);
  if(offres.length!==38)throw new Error('Référentiel PFMP incohérent : 38 classes visibles attendues, '+offres.length+' trouvées.');
  var dBy={},cBy={},pBy={}; diplomes.forEach(function(r){dBy[r.id]=r;});classes.forEach(function(r){cBy[r.id]=r;});periodes.forEach(function(r){pBy[r.id]=r;});
  var periodIdsByOffer={}; relations.forEach(function(r){var o=EUC_PFMP_ref_(r.fields.Offre_formation),p=EUC_PFMP_ref_(r.fields.Periode);if(!periodIdsByOffer[o])periodIdsByOffer[o]=[];periodIdsByOffer[o].push(p);});
  return {version:EUC_PFMP_VERSION,annees:annees.map(function(r){return {id:r.id,code:r.fields.Code||r.fields.Libelle||''};}),offres:offres.sort(function(a,b){return Number(a.fields.Ordre||0)-Number(b.fields.Ordre||0);}).map(function(r){var d=dBy[EUC_PFMP_ref_(r.fields.Diplome)],cl=cBy[EUC_PFMP_ref_(r.fields.Classe)];return {id:r.id,anneeId:EUC_PFMP_ref_(r.fields.Annee_scolaire),diplomeId:d?d.id:null,diplome:r.fields.Libelle_affichage||(d?d.fields.Libelle||d.fields.Code:'Formation à préciser'),classeId:cl?cl.id:null,classe:r.fields.Code_classe||cl&&((cl.fields.Libelle||cl.fields.Nom))||'',periodes:(periodIdsByOffer[r.id]||[]).map(function(id){var p=pBy[id];return p?{id:p.id,libelle:p.fields.Libelle_periode||p.fields.Type||'Période officielle',debut:EUC_PFMP_dateIso_(p.fields.Date_debut),fin:EUC_PFMP_dateIso_(p.fields.Date_fin)}:null;}).filter(Boolean)};})};
}

/** Liste nominative strictement limitée à la classe/année sélectionnée. La date de référence sert à écarter les élèves sortis avant la PFMP. */
function EUC_PFMP_listerElevesPourPeriode(anneeId,offreId,dateReference) {
  EUC_ENT_controlerAccesUtilisateur_(); EUC_ENT_controlerCibleRecette_();
  anneeId=Number(anneeId||0);offreId=Number(offreId||0);dateReference=EUC_PFMP_dateIso_(dateReference);
  if(!anneeId||!offreId)throw new Error('Année scolaire et classe obligatoires.');
  var catalogue=EUC_PFMP_chargerReferentiel(),offre=catalogue.offres.filter(function(o){return o.id===offreId&&o.anneeId===anneeId;})[0];
  if(!offre)throw new Error('Classe absente du référentiel PFMP actif.');
  var rows=EUC_PFMP_lireTable_(EUC_PFMP_TABLES.eleves),actifs=[],sortis=[];
  rows.forEach(function(r){var f=r.fields||{};if(EUC_PFMP_ref_(f.Annee_scolaire)!==anneeId)return;var memeOffre=EUC_PFMP_ref_(f.Offre_formation)===offreId,memeClasse=String(f.Code_classe_importe||'').toUpperCase()===String(offre.classe||'').toUpperCase();if(!memeOffre&&!memeClasse)return;if(f.Actif===false)return;var entree=EUC_PFMP_dateIso_(f.Date_entree),sortie=EUC_PFMP_dateIso_(f.Date_sortie),avantEntree=!!(dateReference&&entree&&entree>dateReference),dejaSorti=!!(dateReference&&sortie&&sortie<dateReference);var item={id:r.id,nom:f.Nom||'',prenom:f.Prenom_usage||f.Prenom||'',dateNaissance:EUC_PFMP_dateIso_(f.Date_naissance),dateEntree:entree,dateSortie:sortie,numeroNational:f.Numero_national||f.Numero_National||'',sorti:dejaSorti};if(avantEntree)return;(dejaSorti?sortis:actifs).push(item);});
  function tri(a,b){return String(a.nom).localeCompare(String(b.nom),'fr',{sensitivity:'base'})||String(a.prenom).localeCompare(String(b.prenom),'fr',{sensitivity:'base'});}
  actifs.sort(tri);sortis.sort(tri);
  return {version:EUC_PFMP_VERSION,classe:offre.classe,dateReference:dateReference,actifs:actifs,sortis:sortis,secoursSaisieLibre:true};
}
function EUC_PFMP_listerContactsEntreprise(entrepriseId) { EUC_ENT_controlerAccesUtilisateur_(); entrepriseId=Number(entrepriseId||0); if(!entrepriseId)return []; return EUC_PFMP_lireTable_(EUC_PFMP_TABLES.contacts).filter(function(r){return EUC_PFMP_ref_(r.fields.Entreprise)===entrepriseId&&r.fields.Actif!==false;}).map(function(r){return {id:r.id,nom:[r.fields.Prenom,r.fields.Nom].filter(Boolean).join(' '),fonction:r.fields.Fonction||'',telephone:r.fields.Telephone_direct||'',courriel:r.fields.Courriel_direct||''};}); }
function EUC_PFMP_nettoyer_(v,max) { return String(v==null?'':v).trim().replace(/[<>]/g,'').slice(0,max||5000); }
function EUC_PFMP_normaliserPays_(p){return EUC_PFMP_nettoyer_(p,100).toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'');}
function EUC_PFMP_formaterTelephone_(chiffres){return String(chiffres).replace(/(\d{2})(?=\d)/g,'$1 ').trim();}
function EUC_PFMP_validerTelephone_(valeur,pays,obligatoire){var brut=EUC_PFMP_nettoyer_(valeur,40);if(!brut)return obligatoire?{valide:false,message:'Téléphone obligatoire.'}:{valide:true,normalise:''};if(!/^[0-9 .()\-]+$/.test(brut)||brut.indexOf('+')>=0)return {valide:false,message:'Le téléphone contient des caractères interdits.'};var ouvert=(brut.match(/\(/g)||[]).length,ferme=(brut.match(/\)/g)||[]).length;if(ouvert!==ferme||ouvert>1)return {valide:false,message:'Parenthèses téléphoniques invalides.'};var chiffres=brut.replace(/[ .()\-]/g,''),p=EUC_PFMP_normaliserPays_(pays);if(p==='france'){if(!/^0[1-9]\d{8}$/.test(chiffres))return {valide:false,message:'Format France attendu : 10 chiffres commençant par 01 à 09.'};}else if(p==='monaco'){var fixe=/^(?:87\d{6}|9\d{7})$/.test(chiffres),mobileCourt=/^(?:3\d{7}|(?:44|45|46)\d{6})$/.test(chiffres),mobileNational=/^0[67]\d{8}$/.test(chiffres),mobileLong=/^2\d{11}$/.test(chiffres);if(!(fixe||mobileCourt||mobileNational||mobileLong))return {valide:false,message:'Numéro national monégasque invalide.'};}else if(!/^\d{6,15}$/.test(chiffres))return {valide:false,message:'Le téléphone national doit contenir de 6 à 15 chiffres.'};return {valide:true,normalise:EUC_PFMP_formaterTelephone_(chiffres)};}
function EUC_PFMP_validerTelephoneProfessionnel_(valeur,pays){var national=EUC_PFMP_validerTelephone_(valeur,pays,false);if(national.valide||!EUC_PFMP_nettoyer_(valeur,40)||EUC_PFMP_normaliserPays_(pays)==='france')return national;return EUC_PFMP_validerTelephone_(valeur,'France',false);}
function EUC_PFMP_validerCoordonnees_(d) {var erreurs=[];['jeuneNom','jeunePrenom','jeuneDateNaissance','jeuneTelephone','jeuneCourriel','jeuneAdresse','jeuneCodePostal','jeuneCommune'].forEach(function(k){if(!EUC_PFMP_nettoyer_(d[k],500))erreurs.push(k+' obligatoire.');});if(d.jeuneCourriel&&!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(d.jeuneCourriel))erreurs.push('Adresse électronique du jeune invalide.');var tel=EUC_PFMP_validerTelephone_(d.jeuneTelephone,'France',true);if(!tel.valide)erreurs.push('Téléphone du jeune invalide : '+tel.message);else d.jeuneTelephone=tel.normalise;if(d.jeuneCodePostal&&!/^[0-9A-Z -]{4,10}$/i.test(d.jeuneCodePostal))erreurs.push('Code postal invalide.');return erreurs;}
function EUC_PFMP_validerDonnees_(d) {var e=EUC_PFMP_validerCoordonnees_(d);if(d.statutJeune==='Scolaire'&&d.scenarioDates==='Dates officielles')d.motif='';if(['Scolaire','Apprenti'].indexOf(d.statutJeune)<0)e.push('Votre statut est obligatoire.');if(!Number(d.offreId))e.push('Classe obligatoire.');if(d.statutJeune==='Scolaire'&&!Number(d.periodeId))e.push('Période officielle obligatoire.');if(!d.dateDeclareeDebut||!d.dateDeclareeFin)e.push('Dates déclarées obligatoires.');if(d.dateDeclareeDebut&&d.dateDeclareeFin&&d.dateDeclareeDebut>d.dateDeclareeFin)e.push('La date de fin doit suivre la date de début.');var scenarios=['Dates officielles','Début retardé','Autre situation exceptionnelle'];if(d.statutJeune==='Scolaire'&&scenarios.indexOf(d.scenarioDates)<0)e.push('Situation de dates non autorisée.');if(d.statutJeune==='Scolaire'&&d.scenarioDates==='Dates officielles'&&(d.dateDeclareeDebut!==d.dateOfficielleDebut||d.dateDeclareeFin!==d.dateOfficielleFin))e.push('Les dates réelles doivent correspondre aux dates officielles.');if(d.statutJeune==='Scolaire'&&d.scenarioDates==='Début retardé'&&d.dateDeclareeFin!==d.dateOfficielleFin)e.push('La fin doit rester la date officielle en cas de début retardé.');if(d.statutJeune==='Scolaire'&&d.scenarioDates!=='Dates officielles'&&!EUC_PFMP_nettoyer_(d.motif,1000))e.push('Motif obligatoire pour cette situation.');if(!d.entrepriseConfirmee)e.push('Vous devez confirmer le bon établissement.');var pays=EUC_PFMP_nettoyer_(d.entreprisePays,100);if(!pays)e.push('Pays de l’entreprise obligatoire.');if(pays.toLowerCase()==='france'&&!EUC_PFMP_nettoyer_(d.entrepriseSiret,20))e.push('SIRET obligatoire pour une entreprise française.');['entrepriseRaisonSociale','entrepriseAdresse','entrepriseCommune','responsableNom'].forEach(function(k){if(!EUC_PFMP_nettoyer_(d[k],500))e.push(k+' obligatoire.');});[['responsableTelephone','responsable'],['tuteurTelephone','tuteur']].forEach(function(item){var t=EUC_PFMP_validerTelephoneProfessionnel_(d[item[0]],pays);if(!t.valide)e.push('Téléphone du '+item[1]+' invalide pour le pays de l’entreprise et pour la France.');else d[item[0]]=t.normalise;});if(!EUC_PFMP_nettoyer_(d.tuteurNom,150))e.push('Nom du tuteur obligatoire.');if(EUC_PFMP_nettoyer_(d.honeypot,100))e.push('Soumission refusée.');if(Number(d.elapsedMs||0)<3000)e.push('Formulaire envoyé trop rapidement.');if(!EUC_PFMP_nettoyer_(d.nonce,200))e.push('Nonce absent.');if(e.length)throw new Error(e.join(' ')); return true;}
function EUC_PFMP_nomComplet_(prenom,nom){return [EUC_PFMP_nettoyer_(prenom,150),EUC_PFMP_nettoyer_(nom,150)].filter(Boolean).join(' ');}
function EUC_PFMP_preparerContactsSimules_(d){var responsable={prenom:EUC_PFMP_nettoyer_(d.responsablePrenom,150),nom:EUC_PFMP_nettoyer_(d.responsableNom,150),fonction:EUC_PFMP_nettoyer_(d.responsableFonction,250),telephone:EUC_PFMP_nettoyer_(d.responsableTelephone,30),courriel:EUC_PFMP_nettoyer_(d.responsableCourriel,250),roles:['Responsable']};if(d.tuteurEstResponsable){responsable.roles.push('Tuteur');return [responsable];}return [responsable,{prenom:EUC_PFMP_nettoyer_(d.tuteurPrenom,150),nom:EUC_PFMP_nettoyer_(d.tuteurNom,150),fonction:EUC_PFMP_nettoyer_(d.tuteurFonction,250),telephone:EUC_PFMP_nettoyer_(d.tuteurTelephone,30),courriel:EUC