/** Eucalyptus PFMP — v1.0.0-dev.117 — PDF vierge + QR ID Grist + continuation entreprise. */
var EUC_PDF_TEMPLATE_PROP_='EUC_PFMP_PDF_TEMPLATE_ID';
var EUC_PDF_TEMPLATE_NAME_='Convention_PFMP_MODELE.pdf';
var EUC_PDF_MIME_='application/pdf';
var EUC_PDF_OUTPUT_FOLDER_='Conventions PDF';
function EUC_PDF_exigerAdmin_(){var ctx=EUC_PFMP_contexteAdmin_();if(!ctx||!ctx.autorise)throw new Error('Accès administrateur requis.');return ctx;}
function EUC_dispatchUploadV95(type,payload){type=String(type||'').toUpperCase();if(type==='DOCX')return EUC_DOCX_importerModele(payload);if(type==='PDF')return EUC_PDF_importerModele(payload);if(type==='LAYOUT_LIST')return EUC_CONVENTION_listerMiseEnPageV529();if(type==='LAYOUT_SAVE')return EUC_CONVENTION_enregistrerMiseEnPageV529(payload);if(type==='LAYOUT_PREVIEW')return EUC_CONVENTION_apercuMiseEnPageV529();throw new Error('Type de modèle ou d’action inconnu.');}
function EUC_PDF_fileByProp_(){var id=PropertiesService.getScriptProperties().getProperty(EUC_PDF_TEMPLATE_PROP_);if(!id)return null;try{var f=DriveApp.getFileById(id);return f.isTrashed()?null:f;}catch(e){return null;}}
function EUC_PDF_modeleInfo(){EUC_PDF_exigerAdmin_();var f=EUC_PDF_fileByProp_(),base='Mon Drive / Eucalyptus PFMP / Modeles';if(!f)return {configure:false,emplacement:base,nom:'',url:'',id:''};return {configure:true,id:f.getId(),nom:f.getName(),url:f.getUrl(),taille:f.getSize(),maj:f.getLastUpdated().toISOString(),emplacement:base+' / '+f.getName()};}
function EUC_PDF_importerModele(payload){EUC_PDF_exigerAdmin_();payload=payload||{};var name=EUC_DOCX_safeName_(payload.nom||EUC_PDF_TEMPLATE_NAME_);if(!/\.pdf$/i.test(name))name+='.pdf';var b64=String(payload.base64||'').replace(/^data:[^,]+,/, '');if(!b64)throw new Error('Fichier PDF manquant.');var bytes=Utilities.base64Decode(b64);if(bytes.length<1000)throw new Error('Le PDF paraît vide ou invalide.');if(bytes.length>8*1024*1024)throw new Error('Le modèle PDF dépasse 8 Mo.');var folder=EUC_DOCX_modelFolder_(),old=EUC_PDF_fileByProp_();if(old)old.setTrashed(true);var f=folder.createFile(Utilities.newBlob(bytes,EUC_PDF_MIME_,name));PropertiesService.getScriptProperties().setProperty(EUC_PDF_TEMPLATE_PROP_,f.getId());CacheService.getScriptCache().remove('EUC_PFMP_PDF_MASTER_B64_V161F9');return EUC_PDF_modeleInfo();}
function EUC_PDF_modeleBase64_(){var cache=CacheService.getScriptCache(),key='EUC_PFMP_PDF_MASTER_B64_V161F9',cached=cache.get(key);if(cached)return cached;var f=EUC_PDF_fileByProp_();if(!f)throw new Error('Aucun modèle PDF actif. Installez le patron PDF vierge 2 pages.');var b64=Utilities.base64Encode(f.getBlob().getBytes());try{cache.put(key,b64,21600);}catch(e){}return b64;}
function EUC_PDF_lireAccesFraisV108_(){var raw=EUC_ENT_grist('get','/tables/'+encodeURIComponent(EUC_CONVENTION_ACCES_TABLE_)+'/records');return (raw.records||[]).map(function(r){var o={id:r.id},f=r.fields||{};Object.keys(f).forEach(function(k){o[k]=f[k];});return o;});}
function EUC_PDF_preparerDataV117_(data,rows,modeles){var token=String(data&&data.token||'').trim(),ref=String(data&&data.reference||'').trim(),requestedId=Number(data&&data.accessId||0);if(!ref||(!token&&!requestedId))throw new Error('Identifiant ou référence de convention absent : QR impossible.');var h=token?EUC_CONVENTION_hash_(token):'',matches=(rows||[]).filter(function(r){return r.Supprimee_admin!==true&&String(r.Reference_convention||'').trim()===ref&&(requestedId?Number(r.id)===requestedId:(r.Revoked!==true&&String(r.Token_hash||'')===h));});if(matches.length!==1)throw new Error('Contrôle QR impossible : la convention n’est pas retrouvée de façon unique dans Grist.');var acces=matches[0],rid=Number(acces.id||0);if(!rid)throw new Error('Identifiant Grist de l’accès absent.');if(!String(data.diplome||'').trim()){
  data.diplome=EUC_CONVENTION_diplomeStrictV108_(data.classeId);
}data.formUrl=ScriptApp.getService().getUrl()+'?page=pfmp&rid='+encodeURIComponent(rid);data.qrReference=ref;data.qrAccessId=rid;data.lignes=EUC_CONVENTION_rendreLignesV108_(data,modeles);data.miseEnPage=typeof EUC_DEV529_miseEnPagePayload_==='function'?EUC_DEV529_miseEnPagePayload_():{};return data;}
function EUC_PDF_payloadTokenV95(token){EUC_PDF_exigerAdmin_();EUC_CONVENTION_resetCacheV94_();var modeles=EUC_CONVENTION_lireModelesLignesV108_(),data=EUC_CONVENTION_donneesImpressionV80(String(token||'')),rows=EUC_PDF_lireAccesFraisV108_();data=EUC_PDF_preparerDataV117_(data,rows,modeles);return {version:'Eucalyptus PFMP — v1.0.0-dev.117',mode:'single',pdfBase64:EUC_PDF_modeleBase64_(),items:[data],filename:'Convention_'+EUC_DOCX_safeName_(data.eleve.nom)+'_'+EUC_DOCX_safeName_(data.eleve.prenom)+'_'+EUC_DOCX_safeName_(data.reference)+'.pdf'};}
function EUC_PDF_payloadAccesIdV525(accesId){EUC_PDF_exigerAdmin_();EUC_CONVENTION_resetCacheV94_();var modeles=EUC_CONVENTION_lireModelesLignesV108_(),data=EUC_CONVENTION_donneesImpressionParIdV525(Number(accesId||0)),rows=EUC_PDF_lireAccesFraisV108_();data=EUC_PDF_preparerDataV117_(data,rows,modeles);return {version:'Eucalyptus PFMP — v1.0.0-dev.526',mode:'single',pdfBase64:EUC_PDF_modeleBase64_(),items:[data],filename:'Convention_'+EUC_DOCX_safeName_(data.eleve.nom)+'_'+EUC_DOCX_safeName_(data.eleve.prenom)+'_'+EUC_DOCX_safeName_(data.reference)+'.pdf'};}
function EUC_PDF_payloadLotV95(lot){EUC_PDF_exigerAdmin_();var d=EUC_CONVENTION_donneesImpressionLot(String(lot||'')),tokens=(d.items||[]).map(function(i){return i.token;}).filter(Boolean);if(!tokens.length)throw new Error('Aucune convention dans ce lot.');if(tokens.length>40)throw new Error('Lot PDF limité à 40 conventions.');EUC_CONVENTION_resetCacheV94_();var modeles=EUC_CONVENTION_lireModelesLignesV108_(),rows=EUC_PDF_lireAccesFraisV108_(),datas=tokens.map(function(t){return EUC_PDF_preparerDataV117_(EUC_CONVENTION_donneesImpressionV80(t),rows,modeles);});return {version:'Eucalyptus PFMP — v1.0.0-dev.117',mode:'batch',pdfBase64:EUC_PDF_modeleBase64_(),items:datas,filename:'LOT_'+EUC_DOCX_safeName_(d.classe||datas[0].classe)+'_'+EUC_DOCX_safeName_(d.annee||datas[0].annee)+'_'+datas.length+'_conventions.pdf'};}
function EUC_PDF_niveauV525_(classe){var c=String(classe||'').trim().toUpperCase();if(/^T/.test(c))return 'Terminale';if(/^1BTS/.test(c))return 'BTS 1';if(/^2BTS/.test(c))return 'BTS 2';if(/^1/.test(c))return 'Premiere';if(/^2/.test(c))return 'Seconde';return 'Niveau non classe';}
function EUC_PDF_archiveFolderV525_(a){
  var root=EUC_DOCX_folder_(EUC_DOCX_root_(),EUC_PDF_OUTPUT_FOLDER_),annee=EUC_DOCX_folder_(root,EUC_DOCX_safeName_(a.Annee_scolaire||'Annee')),
      niveau=EUC_DOCX_folder_(annee,EUC_DOCX_safeName_(EUC_PDF_niveauV525_(a.Classe_convention_nom))),classe=EUC_DOCX_folder_(niveau,EUC_DOCX_safeName_(a.Classe_convention_nom||'Classe')),
      periode=EUC_DOCX_folder_(classe,EUC_DOCX_safeName_([a.Periode_libelle||'PFMP',EUC_IMPORT_dateExistanteISO_(a.Date_debut),EUC_IMPORT_dateExistanteISO_(a.Date_fin)].filter(Boolean).join(' - ')));
  return periode;
}
function EUC_PDF_archiverV525(payload){
  EUC_PDF_exigerAdmin_();payload=payload||{};var ids=(payload.accessIds||[]).map(Number).filter(function(x,i,a){return x>0&&a.indexOf(x)===i;});
  if(!ids.length||ids.length>40)throw new Error('Archive PDF : liste de conventions invalide.');
  var b64=String(payload.base64||'').replace(/^data:[^,]+,/, '');if(!b64)throw new Error('Archive PDF : fichier absent.');
  var bytes=Utilities.base64Decode(b64);if(bytes.length<1000)throw new Error('Archive PDF : fichier vide ou invalide.');if(bytes.length>20*1024*1024)throw new Error('Archive PDF : fichier supérieur à 20 Mo.');
  EUC_CONVENTION_assurerTableAcces_();var all=EUC_PDF_lireAccesFraisV108_(),by={};all.forEach(function(r){by[Number(r.id)]=r;});var rows=ids.map(function(id){return by[id];});
  if(rows.some(function(r){return !r||r.Supprimee_admin===true;}))throw new Error('Archive PDF : une convention est absente ou supprimée.');
  var first=rows[0],same=rows.every(function(r){return String(r.Annee_scolaire||'')===String(first.Annee_scolaire||'')&&String(r.Classe_convention_nom||'')===String(first.Classe_convention_nom||'')&&Number(EUC_PFMP_ref_(r.Periode))===Number(EUC_PFMP_ref_(first.Periode));});
  if(!same)throw new Error('Archive PDF : le lot doit appartenir à une même année, classe et période.');
  var name=EUC_DOCX_safeName_(payload.filename||'Convention_PFMP')+(String(payload.filename||'').toLowerCase().slice(-4)==='.pdf'?'':'.pdf');
  if(ids.length>1){var key=Utilities.base64EncodeWebSafe(Utilities.computeDigest(Utilities.DigestAlgorithm.SHA_256,ids.join(','),Utilities.Charset.UTF_8)).replace(/=+$/,'').substring(0,10);name=name.replace(/\.pdf$/i,'')+'_'+key+'.pdf';}
  var folder=EUC_PDF_archiveFolderV525_(first),old=folder.getFilesByName(name);while(old.hasNext())old.next().setTrashed(true);
  var file=folder.createFile(Utilities.newBlob(bytes,EUC_PDF_MIME_,name)),now=new Date().toISOString(),records=ids.map(function(id){return{id:id,fields:{Drive_pdf_file_id:file.getId(),Drive_pdf_url:file.getUrl(),Drive_pdf_nom:file.getName(),Drive_pdf_date:now,Drive_pdf_taille:bytes.length}};});
  EUC_ENT_grist('patch','/tables/'+encodeURIComponent(EUC_CONVENTION_ACCES_TABLE_)+'/records',{records:records});
  return {ok:true,fileId:file.getId(),url:file.getUrl(),folderUrl:folder.getUrl(),nom:file.getName(),taille:bytes.length,total:ids.length};
}
function EUC_PDF_preparerDataV116_(data,rows,modeles){return EUC_PDF_preparerDataV117_(data,rows,modeles);}
function EUC_PDF_preparerDataV115_(data,rows,modeles){return EUC_PDF_preparerDataV117_(data,rows,modeles);}
function EUC_PDF_preparerDataV113_(data,rows,modeles){return EUC_PDF_preparerDataV117_(data,rows,modeles);}
function EUC_PDF_preparerDataV112_(data,rows,modeles){return EUC_PDF_preparerDataV117_(data,rows,modeles);}
function EUC_PDF_preparerDataV111_(data,rows,modeles){return EUC_PDF_preparerDataV117_(data,rows,modeles);}
function EUC_PDF_preparerDataV110_(data,rows,modeles){return EUC_PDF_preparerDataV117_(data,rows,modeles);}
function EUC_PDF_preparerDataV109_(data,rows,modeles){return EUC_PDF_preparerDataV117_(data,rows,modeles);}
function EUC_PDF_preparerDataV108_(data,rows,modeles){return EUC_PDF_preparerDataV117_(data,rows,modeles);}
