/** Eucalyptus PFMP — v1.0.0-dev.94 — données convention enrichies, cache lot et QR court. */
var EUC_CONV_V94_CACHE_={};
function EUC_CONVENTION_refIdV80_(v){return EUC_PFMP_ref_(v);}
function EUC_CONVENTION_txtV80_(v){return String(v===null||v===undefined?'':v).trim();}
function EUC_CONVENTION_recordsV94_(table){if(!EUC_CONV_V94_CACHE_[table])EUC_CONV_V94_CACHE_[table]=EUC_IMPORT_lireRecords_(table);return EUC_CONV_V94_CACHE_[table];}
function EUC_CONVENTION_resetCacheV94_(){EUC_CONV_V94_CACHE_={};}
function EUC_CONVENTION_adresseV80_(o){o=o||{};return [o.Adresse_1,o.Adresse_2,o.Adresse_3,o.Adresse_4].map(EUC_CONVENTION_txtV80_).filter(Boolean).join(', ');}
function EUC_CONVENTION_telRespV80_(r){return EUC_CONVENTION_txtV80_(r.Telephone_portable||r.Telephone_fixe||r.Telephone_professionnel);}
function EUC_CONVENTION_respScoreV80_(r){var s=0;if(r.Responsable_legal===true)s+=100;if(r.Responsable_en_charge===true)s+=60;if(EUC_CONVENTION_telRespV80_(r))s+=10;if(EUC_CONVENTION_txtV80_(r.Email))s+=10;if(EUC_CONVENTION_adresseV80_(r))s+=5;return s;}
function EUC_CONVENTION_responsablePrioritaireV80_(eleveId){var rows=[];try{rows=EUC_CONVENTION_recordsV94_('EUC_RESPONSABLES_ELEVES_PFMP');}catch(e){return null;}rows=rows.filter(function(r){return EUC_CONVENTION_refIdV80_(r.Eleve)===Number(eleveId);});rows.sort(function(a,b){return EUC_CONVENTION_respScoreV80_(b)-EUC_CONVENTION_respScoreV80_(a)||String(a.Rang_responsable||'').localeCompare(String(b.Rang_responsable||''));});return rows[0]||null;}
function EUC_CONVENTION_compterJoursV80_(debut,fin){if(!debut||!fin)return 0;var d=new Date(debut+'T12:00:00Z'),f=new Date(fin+'T12:00:00Z'),n=0;if(isNaN(d)||isNaN(f)||d>f)return 0;for(;d<=f;d.setUTCDate(d.getUTCDate()+1)){var j=d.getUTCDay();if(j!==0&&j!==6)n++;}return n;}
function EUC_CONVENTION_dateFRV85_(iso,annee4){iso=EUC_CONVENTION_txtV80_(iso);var m=iso.match(/^(\d{4})-(\d{2})-(\d{2})$/);if(!m)return iso;return m[3]+'/'+m[2]+'/'+(annee4?m[1]:m[1].slice(2));}
function EUC_CONVENTION_telFRV85_(v){var brut=EUC_CONVENTION_txtV80_(v);if(!brut)return '';var chiffres=brut.replace(/\D/g,'');if(/^0033[1-9]\d{8}$/.test(chiffres))chiffres='0'+chiffres.slice(4);else if(/^33[1-9]\d{8}$/.test(chiffres))chiffres='0'+chiffres.slice(2);else if(/^[1-9]\d{8}$/.test(chiffres))chiffres='0'+chiffres;if(/^0[1-9]\d{8}$/.test(chiffres))return chiffres.replace(/(\d{2})(?=\d)/g,'$1 ').trim();return brut;}
function EUC_CONVENTION_coordonneesV80_(e){var r=EUC_CONVENTION_responsablePrioritaireV80_(e.id),adresseEleve=EUC_CONVENTION_adresseV80_(e),adresseResp=EUC_CONVENTION_adresseV80_(r||{}),cp=EUC_CONVENTION_txtV80_(e.Code_postal),ville=EUC_CONVENTION_txtV80_(e.Ville),pays=EUC_CONVENTION_txtV80_(e.Pays),email=EUC_CONVENTION_txtV80_(e.Email_eleve||e.Courriel),tel=EUC_CONVENTION_txtV80_(e.Telephone_eleve||e.Telephone);if(!adresseEleve&&r){adresseEleve=adresseResp;cp=EUC_CONVENTION_txtV80_(r.Code_postal);ville=EUC_CONVENTION_txtV80_(r.Ville);pays=EUC_CONVENTION_txtV80_(r.Pays);}if(!email&&r)email=EUC_CONVENTION_txtV80_(r.Email);if(!tel&&r)tel=EUC_CONVENTION_telRespV80_(r);tel=EUC_CONVENTION_telFRV85_(tel);return {adresse:adresseEleve,codePostal:cp,ville:ville,pays:pays,email:email,telephone:tel,responsable:r?{nom:EUC_CONVENTION_txtV80_(r.Nom),prenom:EUC_CONVENTION_txtV80_(r.Prenom),lien:EUC_CONVENTION_txtV80_(r.Lien_avec_eleve),type:EUC_CONVENTION_txtV80_(r.Type_responsabilite)}:null,sourceEmail:EUC_CONVENTION_txtV80_(e.Email_eleve||e.Courriel)?'ELEVE':(email?'RESPONSABLE':''),sourceTelephone:EUC_CONVENTION_txtV80_(e.Telephone_eleve||e.Telephone)?'ELEVE':(tel?'RESPONSABLE':'')};}
function EUC_CONVENTION_professeursPrincipauxV84_(classeId,fallback){var out=[];try{var links=EUC_CONVENTION_recordsV94_('EUC_CLASSES_PROFESSEURS_PFMP').filter(function(r){return r.Actif!==false&&String(r.Role||'')==='PROFESSEUR_PRINCIPAL'&&EUC_CONVENTION_refIdV80_(r.Classe)===Number(classeId);});var profs=EUC_CONVENTION_recordsV94_('EUC_PROFESSEURS_PFMP'),byId={};profs.forEach(function(p){byId[p.id]=p;});links.forEach(function(l){var p=byId[EUC_CONVENTION_refIdV80_(l.Professeur)];if(!p)return;out.push({nom:[EUC_CONVENTION_txtV80_(p.Civilite),EUC_CONVENTION_txtV80_(p.Prenom),EUC_CONVENTION_txtV80_(p.Nom)].filter(Boolean).join(' '),email:EUC_CONVENTION_txtV80_(p.Email),discipline:EUC_CONVENTION_txtV80_(p.Discipline)});});}catch(e){}if(!out.length&&fallback)out.push({nom:EUC_CONVENTION_txtV80_(fallback),email:'',discipline:''});return out;}
function EUC_CONVENTION_diplomeV94_(classeId,e){try{var rows=EUC_CONVENTION_recordsV94_('EUC_CLASSES_DIPLOMES_PFMP').filter(function(r){return r.Actif!==false&&String(EUC_CONVENTION_refIdV80_(r.Classe))===String(classeId);});if(rows.length)return EUC_CONVENTION_txtV80_(rows[0].Intitule_diplome);}catch(err){}return EUC_CONVENTION_txtV80_(e.Formation_Pronote||e.Formation||'');}
function EUC_CONVENTION_etablissementV94_(classeId){var etab='';try{var c=EUC_CONVENTION_recordsV94_('Classes').filter(function(r){return r.id===Number(classeId);})[0];if(c)etab=String(c.Etab||c.Etablissement||c.Etablissement_Pronote||'').toUpperCase();}catch(e){}var p={};try{EUC_CONVENTION_recordsV94_('EUC_PARAMETRES_CONVENTION_PFMP').filter(function(r){return r.Actif!==false;}).forEach(function(r){p[String(r.Cle||'')]=String(r.Valeur||'');});}catch(e2){}var lgt=(etab.indexOf('LGT')>=0||etab.indexOf('LYCEE GENERAL')>=0||etab.indexOf('LYCÉE GÉNÉRAL')>=0);return {code:lgt?'LGT':'LP',libelle:lgt?(p.ETABLISSEMENT_LGT||'Lycée Général et Technologique Les Eucalyptus'):(p.ETABLISSEMENT_LP||'Lycée Professionnel Les Eucalyptus'),proviseur:p.PROVISEUR||'Stéphane DEVIN',fonctionProviseur:p.FONCTION_PROVISEUR||'Proviseur',adresse:p.ADRESSE||'7 avenue des Eucalyptus, 06200 NICE',telephone:p.TELEPHONE||'04 92 29 30 65',email:p.EMAIL||'bfe@lycee-les-eucalyptus.org'};}
function EUC_CONVENTION_accesParTokenV94_(token){var hash=EUC_CONVENTION_hash_(token),rows=EUC_CONVENTION_recordsV94_(EUC_CONVENTION_ACCES_TABLE_);var r=rows.filter(function(x){return x.Token_hash===hash&&x.Revoked!==true;})[0];if(!r)throw new Error('Lien de convention invalide ou révoqué.');return r;}
function EUC_CONVENTION_qrCodeCourtV94_(token){return EUC_CONVENTION_hash_(token).substring(0,18);}
function EUC_CONVENTION_donneesImpressionV80(token){var a=EUC_CONVENTION_accesParTokenV94_(token),rows=EUC_CONVENTION_recordsV94_('EUC_ELEVES_PFMP'),e=rows.filter(function(x){return x.id===EUC_CONVENTION_refIdV80_(a.Eleve);})[0];if(!e)throw new Error('Élève introuvable.');var debut=EUC_IMPORT_dateExistanteISO_(a.Date_debut),fin=EUC_IMPORT_dateExistanteISO_(a.Date_fin),naissance=EUC_IMPORT_dateExistanteISO_(e.Date_naissance),c=EUC_CONVENTION_coordonneesV80_(e),pdifMode=String(a.PDIF_mode||''),classeId=EUC_CONVENTION_refIdV80_(a.Classe_convention),pps=EUC_CONVENTION_professeursPrincipauxV84_(classeId,e.Professeur_principal),diplome=EUC_CONVENTION_diplomeV94_(classeId,e),etab=EUC_CONVENTION_etablissementV94_(classeId),q=EUC_CONVENTION_qrCodeCourtV94_(token);return {reference:a.Reference_convention||'',token:String(token||''),qrCode:q,formUrl:ScriptApp.getService().getUrl()+'?page=pfmp&q='+encodeURIComponent(q),annee:a.Annee_scolaire||'',classe:a.Classe_convention_nom||'',classeId:classeId,debut:EUC_CONVENTION_dateFRV85_(debut,true),fin:EUC_CONVENTION_dateFRV85_(fin,true),debutCourt:EUC_CONVENTION_dateFRV85_(debut,false),finCourt:EUC_CONVENTION_dateFRV85_(fin,false),debutISO:debut,finISO:fin,jours:EUC_CONVENTION_compterJoursV80_(debut,fin),pdifMode:pdifMode,etablissement:etab,professeurReferent:pps.map(function(p){return p.nom;}).filter(Boolean).join(' / '),professeursReferents:pps,professeurReferentEmail:pps.map(function(p){return p.email;}).filter(Boolean).join(' / '),diplome:diplome,eleve:{nom:EUC_CONVENTION_txtV80_(e.Nom),prenom:EUC_CONVENTION_txtV80_(e.Prenom_usage||e.Prenom),dateNaissance:EUC_CONVENTION_dateFRV85_(naissance,true),dateNaissanceISO:naissance,adresse:c.adresse,codePostal:c.codePostal,ville:c.ville,pays:c.pays,telephone:c.telephone,courriel:c.email,formation:diplome,responsable:c.responsable,sourceTelephone:c.sourceTelephone,sourceEmail:c.sourceEmail}};}
