/** Eucalyptus PFMP — v1.0.0-dev.61 — copier-coller Pronote + correspondance / exclusion classes Camin + multi-source. */
function EUC_IMPORT_exigerAdminTexte_(){
  var ctx=EUC_PFMP_contexteAdmin_();
  if(!ctx||!ctx.autorise||['DDFPT','ADMIN_PFMP','BUREAU_ENTREPRISES'].indexOf(ctx.role)<0) throw new Error('Accès non autorisé.');
  return ctx;
}
function EUC_IMPORT_lireRecordsBruts_(table){try{return (EUC_ENT_grist('get','/tables/'+encodeURIComponent(table)+'/records').records||[]);}catch(e){return [];}}
function EUC_IMPORT_lireRecords_(table){return EUC_IMPORT_lireRecordsBruts_(table).map(function(r){return Object.assign({id:r.id},r.fields||{});});}
function EUC_IMPORT_chargerClassesCamin_(){return EUC_IMPORT_lireRecordsBruts_('Classes').map(function(r){var f=r.fields||{};return {id:r.id,nom:String(f.Nom||f.Libelle||'').trim(),libelle:String(f.Libelle||f.Nom||'').trim(),formation:String(f.Formation||'').trim(),niveau:String(f.Niveau||'').trim(),actif:f.Actif!==false};}).filter(function(r){return r.id&&r.nom;});}
function EUC_IMPORT_normaliserSourcePronote_(v){return String(v||'').trim().toUpperCase().replace(/\s+/g,'_').replace(/[^A-Z0-9_-]/g,'_').replace(/_+/g,'_').replace(/^_|_$/g,'');}
function EUC_IMPORT_chargerCorrespondances_(annee,sourcePronote){
  var source=EUC_IMPORT_normaliserSourcePronote_(sourcePronote);
  return EUC_IMPORT_lireRecords_('EUC_CORRESPONDANCE_CLASSES_PRONOTE').filter(function(r){var rs=EUC_IMPORT_normaliserSourcePronote_(r.Source_Pronote||'');return r.Actif!==false&&(!r.Annee_scolaire||String(r.Annee_scolaire)===String(annee))&&(!rs||rs===source);}).map(function(r){return {pronote:String(r.Nom_classe_Pronote||'').trim(),classeId:r.Classe_Grist||'',classeNom:String(r.Classe_Grist_nom||r.Classe_Grist_libelle||'').trim(),exclue:r.Exclure_import===true};});
}
function EUC_IMPORT_indexerCorrespondances_(classes,mappingsPersistes,mappingsTemporaires){var byId={},byNom={},map={};(classes||[]).forEach(function(c){byId[String(c.id)]=c;byNom[String(c.nom).toUpperCase()]=c;byNom[String(c.libelle).toUpperCase()]=c;});function add(pronote,idOrNom){var key=String(pronote||'').trim().toUpperCase();if(!key)return;var c=byId[String(idOrNom)]||byNom[String(idOrNom||'').trim().toUpperCase()];if(c&&c.actif)map[key]=c;}(mappingsPersistes||[]).forEach(function(m){if(!m.exclue)add(m.pronote,m.classeId||m.classeNom);});Object.keys(mappingsTemporaires||{}).forEach(function(k){add(k,mappingsTemporaires[k]);});(classes||[]).forEach(function(c){if(c.actif){var k=String(c.nom).toUpperCase();if(!map[k])map[k]=c;var l=String(c.libelle).toUpperCase();if(!map[l])map[l]=c;}});return map;}
function EUC_IMPORT_indexExclusions_(mappingsPersistes,exclusionsTemporaires){var out={};(mappingsPersistes||[]).forEach(function(m){if(m.exclue&&m.pronote)out[String(m.pronote).trim().toUpperCase()]=true;});(exclusionsTemporaires||[]).forEach(function(n){if(n)out[String(n).trim().toUpperCase()]=true;});return out;}
function EUC_IMPORT_preparerClasses_(parsed,classes,mappingsPersistes,mappingsTemporaires,exclusionsTemporaires){
  var index=EUC_IMPORT_indexerCorrespondances_(classes,mappingsPersistes,mappingsTemporaires),exclusions=EUC_IMPORT_indexExclusions_(mappingsPersistes,exclusionsTemporaires),stats={},inconnues={},exclues={},rows=[];
  parsed.rows.forEach(function(r){var original=String(r.classe||'').trim();r.classePronote=original;if(!original){rows.push(r);return;}stats[original]=(stats[original]||0)+1;if(exclusions[original.toUpperCase()]){exclues[original]=(exclues[original]||0)+1;r._exclueImport=true;return;}var c=index[original.toUpperCase()];if(c){r.classe=c.nom;r.classeGristId=c.id;}else{inconnues[original]=(inconnues[original]||0)+1;r.classe='__NON_CORRESPONDUE__'+original;}rows.push(r);});parsed.rows=rows;
  return {classesPronote:Object.keys(stats).sort(function(a,b){return a.localeCompare(b,'fr');}).map(function(n){var c=index[n.toUpperCase()],x=!!exclusions[n.toUpperCase()];return {pronote:n,effectif:stats[n],correspondue:!!c,classeGristId:c?c.id:'',classeGristNom:c?c.nom:'',exclue:x};}),inconnues:Object.keys(inconnues).sort(function(a,b){return a.localeCompare(b,'fr');}).map(function(n){return {pronote:n,effectif:inconnues[n]};}),exclues:Object.keys(exclues).sort(function(a,b){return a.localeCompare(b,'fr');}).map(function(n){return {pronote:n,effectif:exclues[n]};}),effectifExclu:Object.keys(exclues).reduce(function(s,n){return s+exclues[n];},0)};
}
function EUC_IMPORT_chargerDonneesPreviewTexte_(annee,sourcePronote){
  var existing=[],imports=[],source=EUC_IMPORT_normaliserSourcePronote_(sourcePronote);
  try{existing=EUC_SUIVI_fields_(EUC_SUIVI_sqlLecture_("SELECT e.*,a.Code AS Annee_code FROM EUC_ELEVES_PFMP e JOIN Annees_Scolaires a ON a.id=e.Annee_scolaire WHERE a.Code=?",[annee]));}catch(e){}
  if(source){existing=existing.filter(function(e){var es=EUC_IMPORT_normaliserSourcePronote_(e.Source_Pronote||e.Source_import||'');return !es||es===source;});}
  try{imports=EUC_IMPORT_lireRecords_('EUC_IMPORTS_PRONOTE_PFMP').filter(function(i){var is=EUC_IMPORT_normaliserSourcePronote_(i.Source_Pronote||'');return !is||is===source;});}catch(e){}
  return {existing:existing,imports:imports,classes:EUC_IMPORT_chargerClassesCamin_(),correspondances:EUC_IMPORT_chargerCorrespondances_(annee,source)};
}
function EUC_IMPORT_previsualiserTexte(payload){
  EUC_IMPORT_exigerAdminTexte_();payload=payload||{};var texte=String(payload.texte||''),source=EUC_IMPORT_normaliserSourcePronote_(payload.sourcePronote||'');if(!source)throw new Error('Source Pronote obligatoire.');if(!texte.trim()) throw new Error('Aucune donnée Pronote collée.');
  var parsed=EUC_IMPORT_analyserTexte_(texte,{annee:payload.annee});parsed.encoding='COPIER_COLLER';parsed.sourcePronote=source;parsed.empreinte=EUC_IMPORT_empreinte_(Utilities.newBlob(source+'\n'+texte,'text/plain').getBytes());
  var d=EUC_IMPORT_chargerDonneesPreviewTexte_(parsed.annee,source),corr=EUC_IMPORT_preparerClasses_(parsed,d.classes,d.correspondances,payload.correspondances||{},payload.classesExclues||[]),offers=d.classes.filter(function(c){return c.actif;}).map(function(c){return {Code_classe:c.nom,Actif:true,Afficher_formulaire_PFMP:true};}),preview=EUC_IMPORT_previsualiser_(parsed,d.existing,offers,d.imports);
  preview.sourcePronote=source;preview.classesCamin=d.classes.filter(function(c){return c.actif;});preview.classesPronote=corr.classesPronote;preview.classesInconnues=corr.inconnues;preview.classesExclues=corr.exclues;preview.tableCorrespondancePresente=d.correspondances.length>0;preview.correspondancesTemporaires=true;preview.compteurs.classesCaminDisponibles=preview.classesCamin.length;preview.compteurs.classesInconnues=corr.inconnues.length;preview.compteurs.classesEcartees=corr.exclues.length;preview.compteurs.elevesEcartes=corr.effectifExclu;preview.pretAValider=preview.pretAValider&&corr.inconnues.length===0;return preview;
}
function EUC_IMPORT_confirmerSimulationTexte(payload){var lock=LockService.getScriptLock();if(!lock.tryLock(1000)) throw new Error('Un autre import est déjà en cours.');try{EUC_IMPORT_exigerAdminTexte_();if(!payload||payload.confirmation!=='CONFIRMER_IMPORT') throw new Error('Validation humaine explicite obligatoire.');var mode=PropertiesService.getScriptProperties().getProperty('EUC_PFMP_PRONOTE_IMPORT_MODE')||'DRY_RUN';if(mode!=='DRY_RUN') throw new Error('Import réel non autorisé dans cette version.');var preview=EUC_IMPORT_previsualiserTexte(payload);if(!preview.pretAValider) throw new Error(preview.dejaImporte?'Fichier identique déjà importé.':'Prévisualisation bloquée par des anomalies ou classes non correspondantes.');return {statut:'SIMULATION',mode:'DRY_RUN',ecriture:false,sourcePronote:preview.sourcePronote,empreinte:preview.empreinte,compteurs:preview.compteurs};}finally{lock.releaseLock();}}
